-- autogenerated lush spec on Sat 19 Aug 2023 03:58:55 PM EDT
-- Run :Lushify
-- then /Normal to find the Normal group and edit your fg & bg colors
local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv
local theme = lush(function(injected_functions)
  local sym = injected_functions.sym
  return {
    SpecialKey                                                    { bg="#141414", fg="#e7e7e7", }, -- SpecialKey     xxx ctermfg=81 guifg=#e7e7e7 guibg=#141414
    TermCursor                                                    { gui="reverse", }, -- TermCursor     xxx cterm=reverse gui=reverse
    NonText                                                       { gui="bold", bg="#141414", fg="#3d3d3d", }, -- NonText        xxx ctermfg=12 gui=bold guifg=#3d3d3d guibg=#141414
    Whitespace                                                    { NonText }, -- Whitespace     xxx links to NonText
    LspInlayHint                                                  { NonText }, -- LspInlayHint   xxx links to NonText
    sym"@neorg.markup.verbatim.delimiter"                         { NonText }, -- @neorg.markup.verbatim.delimiter xxx links to NonText
    sym"@neorg.markup.superscript.delimiter"                      { NonText }, -- @neorg.markup.superscript.delimiter xxx links to NonText
    sym"@neorg.markup.variable.delimiter"                         { NonText }, -- @neorg.markup.variable.delimiter xxx links to NonText
    sym"@neorg.markup.inline_comment.delimiter"                   { NonText }, -- @neorg.markup.inline_comment.delimiter xxx links to NonText
    sym"@neorg.markup.free_form_delimiter"                        { NonText }, -- @neorg.markup.free_form_delimiter xxx links to NonText
    sym"@neorg.markup.bold.delimiter"                             { NonText }, -- @neorg.markup.bold.delimiter xxx links to NonText
    sym"@neorg.markup.italic.delimiter"                           { NonText }, -- @neorg.markup.italic.delimiter xxx links to NonText
    sym"@neorg.markup.underline.delimiter"                        { NonText }, -- @neorg.markup.underline.delimiter xxx links to NonText
    sym"@neorg.markup.inline_math.delimiter"                      { NonText }, -- @neorg.markup.inline_math.delimiter xxx links to NonText
    sym"@neorg.markup.strikethrough.delimiter"                    { NonText }, -- @neorg.markup.strikethrough.delimiter xxx links to NonText
    sym"@neorg.markup.subscript.delimiter"                        { NonText }, -- @neorg.markup.subscript.delimiter xxx links to NonText
    sym"@neorg.markup.spoiler.delimiter"                          { NonText }, -- @neorg.markup.spoiler.delimiter xxx links to NonText
    sym"@neorg.todo_items.cancelled"                              { NonText }, -- @neorg.todo_items.cancelled xxx links to NonText
    sym"@neorg.anchors.declaration.delimiter"                     { NonText }, -- @neorg.anchors.declaration.delimiter xxx links to NonText
    sym"@neorg.anchors.definition.delimiter"                      { NonText }, -- @neorg.anchors.definition.delimiter xxx links to NonText
    sym"@neorg.modifiers.link"                                    { NonText }, -- @neorg.modifiers.link xxx links to NonText
    sym"@neorg.links.location.delimiter"                          { NonText }, -- @neorg.links.location.delimiter xxx links to NonText
    sym"@neorg.links.description.delimiter"                       { NonText }, -- @neorg.links.description.delimiter xxx links to NonText
    sym"@neorg.links.file.delimiter"                              { NonText }, -- @neorg.links.file.delimiter xxx links to NonText
    Directory                                                     { fg="#d4d4d4", }, -- Directory      xxx ctermfg=159 guifg=#d4d4d4
    ErrorMsg                                                      { gui="bold", bg="#141414", fg="#ff0000", }, -- ErrorMsg       xxx ctermfg=15 ctermbg=1 gui=bold guifg=#ff0000 guibg=#141414
    NvimInvalidSpacing                                            { ErrorMsg }, -- NvimInvalidSpacing xxx links to ErrorMsg
    IncSearch                                                     { gui="reverse", bg="#848586", fg="#000000", }, -- IncSearch      xxx cterm=reverse gui=reverse guifg=#000000 guibg=#848586
    Search                                                        { gui="underline", bg="yellow", fg="black", }, -- Search         xxx ctermfg=0 ctermbg=11 gui=underline guifg=Black guibg=Yellow
    CurSearch                                                     { Search }, -- CurSearch      xxx links to Search
    QuickFixLine                                                  { Search }, -- QuickFixLine   xxx links to Search
    Substitute                                                    { Search }, -- Substitute     xxx links to Search
    CocHoverRange                                                 { Search }, -- CocHoverRange  xxx links to Search
    CocCursorRange                                                { Search }, -- CocCursorRange xxx links to Search
    MoreMsg                                                       { gui="bold", fg="seagreen", }, -- MoreMsg        xxx ctermfg=121 gui=bold guifg=SeaGreen
    CocSymbolDefault                                              { MoreMsg }, -- CocSymbolDefault xxx links to MoreMsg
    ModeMsg                                                       { gui="bold", }, -- ModeMsg        xxx cterm=bold gui=bold
    CocListMode                                                   { ModeMsg }, -- CocListMode    xxx links to ModeMsg
    LineNr                                                        { bg="#141414", fg="#e7e7e7", }, -- LineNr         xxx ctermfg=11 guifg=#e7e7e7 guibg=#141414
    LineNrAbove                                                   { LineNr }, -- LineNrAbove    xxx links to LineNr
    LineNrBelow                                                   { LineNr }, -- LineNrBelow    xxx links to LineNr
    CursorLineNr                                                  { gui="bold", bg="#141414", fg="#fbfbfb", }, -- CursorLineNr   xxx cterm=underline ctermfg=11 gui=bold guifg=#fbfbfb guibg=#141414
    Question                                                      { gui="bold", fg="green", }, -- Question       xxx ctermfg=121 gui=bold guifg=Green
    StatusLine                                                    { gui="bold", bg="#292929", fg="#e7e7e7", }, -- StatusLine     xxx cterm=bold,reverse gui=bold guifg=#e7e7e7 guibg=#292929
    MsgSeparator                                                  { StatusLine }, -- MsgSeparator   xxx links to StatusLine
    StatusLineNC                                                  { gui="reverse", }, -- StatusLineNC   xxx cterm=reverse gui=reverse
    VertSplit                                                     { bg="#292929", fg="#d3d3d3", }, -- VertSplit      xxx guifg=#d3d3d3 guibg=#292929
    WinSeparator                                                  { VertSplit }, -- WinSeparator   xxx links to VertSplit
    Title                                                         { gui="bold", fg="#fbfbfb", }, -- Title          xxx ctermfg=225 gui=bold guifg=#fbfbfb
    FloatTitle                                                    { Title }, -- FloatTitle     xxx links to Title
    sym"@text.title"                                              { Title }, -- @text.title    xxx links to Title
    CocTreeTitle                                                  { Title }, -- CocTreeTitle   xxx links to Title
    Visual                                                        { bg="darkgrey", }, -- Visual         xxx ctermbg=242 guibg=DarkGrey
    CocSnippetVisual                                              { Visual }, -- CocSnippetVisual xxx links to Visual
    WarningMsg                                                    { bg="#ff8800", fg="#fbfbfb", }, -- WarningMsg     xxx ctermfg=224 guifg=#fbfbfb guibg=#ff8800
    WildMenu                                                      { bg="#000000", fg="#484848", }, -- WildMenu       xxx ctermfg=0 ctermbg=11 guifg=#484848 guibg=#000000
    Folded                                                        { bg="#000000", fg="#bfbfbf", }, -- Folded         xxx ctermfg=14 guifg=#bfbfbf guibg=#000000
    FoldColumn                                                    { bg="#141414", fg="#484848", }, -- FoldColumn     xxx ctermfg=14 ctermbg=242 guifg=#484848 guibg=#141414
    CursorLineFold                                                { FoldColumn }, -- CursorLineFold xxx links to FoldColumn
    DiffAdd                                                       { gui="bold", bg="#123d0f", fg="#fafafa", }, -- DiffAdd        xxx ctermbg=4 gui=bold guifg=#fafafa guibg=#123d0f
    DiffChange                                                    { bg="#151b3c", fg="#fafafa", }, -- DiffChange     xxx ctermbg=5 guifg=#fafafa guibg=#151b3c
    DiffDelete                                                    { gui="bold", bg="#141414", fg="blue", }, -- DiffDelete     xxx ctermfg=12 ctermbg=6 gui=bold guifg=Blue guibg=#141414
    DiffText                                                      { gui="bold", bg="#ff0000", fg="#ffffff", }, -- DiffText       xxx cterm=bold ctermbg=9 gui=bold guifg=#ffffff guibg=#ff0000
    SignColumn                                                    { bg="#141414", fg="#484848", }, -- SignColumn     xxx ctermfg=14 guifg=#484848 guibg=#141414
    CursorLineSign                                                { SignColumn }, -- CursorLineSign xxx links to SignColumn
    Conceal                                                       { bg="darkgrey", fg="lightgrey", }, -- Conceal        xxx ctermfg=7 ctermbg=242 guifg=LightGrey guibg=DarkGrey
    CocFadeOut                                                    { Conceal }, -- CocFadeOut     xxx links to Conceal
    SpellBad                                                      { gui="undercurl", sp="red", }, -- SpellBad       xxx ctermbg=9 gui=undercurl guisp=Red
    SpellCap                                                      { gui="undercurl", sp="blue", }, -- SpellCap       xxx ctermbg=12 gui=undercurl guisp=Blue
    SpellRare                                                     { gui="undercurl", sp="magenta", }, -- SpellRare      xxx ctermbg=13 gui=undercurl guisp=Magenta
    SpellLocal                                                    { gui="undercurl", sp="cyan", }, -- SpellLocal     xxx ctermbg=14 gui=undercurl guisp=Cyan
    Pmenu                                                         { bg="#141414", fg="#fbfbfb", }, -- Pmenu          xxx ctermfg=0 ctermbg=13 guifg=#fbfbfb guibg=#141414
    PmenuKind                                                     { Pmenu }, -- PmenuKind      xxx links to Pmenu
    PmenuExtra                                                    { Pmenu }, -- PmenuExtra     xxx links to Pmenu
    NormalFloat                                                   { Pmenu }, -- NormalFloat    xxx links to Pmenu
    PmenuSel                                                      { bg="#292929", }, -- PmenuSel       xxx ctermfg=242 ctermbg=0 guibg=#292929
    PmenuKindSel                                                  { PmenuSel }, -- PmenuKindSel   xxx links to PmenuSel
    PmenuExtraSel                                                 { PmenuSel }, -- PmenuExtraSel  xxx links to PmenuSel
    PmenuSbar                                                     { bg="grey", }, -- PmenuSbar      xxx ctermbg=248 guibg=Grey
    CocFloatSbar                                                  { PmenuSbar }, -- CocFloatSbar   xxx links to PmenuSbar
    PmenuThumb                                                    { bg="white", }, -- PmenuThumb     xxx ctermbg=15 guibg=White
    CocFloatThumb                                                 { PmenuThumb }, -- CocFloatThumb  xxx links to PmenuThumb
    TabLine                                                       { gui="underline", bg="darkgrey", }, -- TabLine        xxx cterm=underline ctermfg=15 ctermbg=242 gui=underline guibg=DarkGrey
    TabLineSel                                                    { gui="bold", }, -- TabLineSel     xxx cterm=bold gui=bold
    TabLineFill                                                   { gui="reverse", }, -- TabLineFill    xxx cterm=reverse gui=reverse
    CursorColumn                                                  { bg="#141414", }, -- CursorColumn   xxx ctermbg=242 guibg=#141414
    CocHighlightText                                              { CursorColumn }, -- CocHighlightText xxx links to CursorColumn
    CursorLine                                                    { bg="#141414", }, -- CursorLine     xxx cterm=underline guibg=#141414
    CocTreeSelected                                               { CursorLine }, -- CocTreeSelected xxx links to CursorLine
    ColorColumn                                                   { bg="#141414", }, -- ColorColumn    xxx ctermbg=1 guibg=#141414
    WinBar                                                        { gui="bold", }, -- WinBar         xxx cterm=bold gui=bold
    WinBarNC                                                      { WinBar }, -- WinBarNC       xxx links to WinBar
    Cursor                                                        { bg="#fbfbfb", fg="#000000", }, -- Cursor         xxx guifg=#000000 guibg=#fbfbfb
    lCursor                                                       { bg="fg", fg="bg", }, -- lCursor        xxx guifg=bg guibg=fg
    Normal                                                        { bg="#000000", fg="#fbfbfb", }, -- Normal         xxx guifg=#fbfbfb guibg=#000000
    NvimSpacing                                                   { Normal }, -- NvimSpacing    xxx links to Normal
    FloatShadow                                                   { bg="black", blend=80, }, -- FloatShadow    xxx guibg=Black blend=80
    FloatShadowThrough                                            { bg="black", blend=100, }, -- FloatShadowThrough xxx guibg=Black blend=100
    RedrawDebugNormal                                             { gui="reverse", }, -- RedrawDebugNormal xxx cterm=reverse gui=reverse
    RedrawDebugClear                                              { bg="yellow", }, -- RedrawDebugClear xxx ctermbg=11 guibg=Yellow
    RedrawDebugComposed                                           { bg="green", }, -- RedrawDebugComposed xxx ctermbg=10 guibg=Green
    RedrawDebugRecompose                                          { bg="red", }, -- RedrawDebugRecompose xxx ctermbg=9 guibg=Red
    Error                                                         { bg="red", fg="white", }, -- Error          xxx ctermfg=15 ctermbg=9 guifg=White guibg=Red
    NvimInvalid                                                   { Error }, -- NvimInvalid    xxx links to Error
    Todo                                                          { gui="bold,reverse", bg="#000000", fg="#e7e7e7", }, -- Todo           xxx ctermfg=0 ctermbg=11 gui=bold,reverse guifg=#e7e7e7 guibg=#000000
    sym"@text.todo"                                               { Todo }, -- @text.todo     xxx links to Todo
    String                                                        { fg="#484848", }, -- String         xxx guifg=#484848
    sym"@string"                                                  { String }, -- @string        xxx links to String
    NvimString                                                    { String }, -- NvimString     xxx links to String
    Constant                                                      { fg="#d4d4d4", }, -- Constant       xxx ctermfg=13 guifg=#d4d4d4
    sym"@constant"                                                { Constant }, -- @constant      xxx links to Constant
    sym"@lsp.type.enumMember"                                     { Constant }, -- @lsp.type.enumMember xxx links to Constant
    Character                                                     { fg="#d4d4d4", }, -- Character      xxx guifg=#d4d4d4
    sym"@character"                                               { Character }, -- @character     xxx links to Character
    Number                                                        { fg="#d4d4d4", }, -- Number         xxx guifg=#d4d4d4
    sym"@number"                                                  { Number }, -- @number        xxx links to Number
    NvimNumber                                                    { Number }, -- NvimNumber     xxx links to Number
    Boolean                                                       { fg="#d4d4d4", }, -- Boolean        xxx guifg=#d4d4d4
    sym"@boolean"                                                 { Boolean }, -- @boolean       xxx links to Boolean
    Float                                                         { fg="#d4d4d4", }, -- Float          xxx guifg=#d4d4d4
    sym"@float"                                                   { Float }, -- @float         xxx links to Float
    Function                                                      { fg="#fbfbfb", }, -- Function       xxx guifg=#fbfbfb
    sym"@function"                                                { Function }, -- @function      xxx links to Function
    sym"@method"                                                  { Function }, -- @method        xxx links to Function
    sym"@lsp.type.decorator"                                      { Function }, -- @lsp.type.decorator xxx links to Function
    sym"@lsp.type.function"                                       { Function }, -- @lsp.type.function xxx links to Function
    sym"@lsp.type.method"                                         { Function }, -- @lsp.type.method xxx links to Function
    Identifier                                                    { gui="italic", fg="#d4d4d4", }, -- Identifier     xxx cterm=bold ctermfg=14 gui=italic guifg=#d4d4d4
    sym"@text.reference"                                          { Identifier }, -- @text.reference xxx links to Identifier
    sym"@parameter"                                               { Identifier }, -- @parameter     xxx links to Identifier
    sym"@field"                                                   { Identifier }, -- @field         xxx links to Identifier
    sym"@property"                                                { Identifier }, -- @property      xxx links to Identifier
    sym"@variable"                                                { Identifier }, -- @variable      xxx links to Identifier
    sym"@namespace"                                               { Identifier }, -- @namespace     xxx links to Identifier
    sym"@lsp.type.parameter"                                      { Identifier }, -- @lsp.type.parameter xxx links to Identifier
    sym"@lsp.type.property"                                       { Identifier }, -- @lsp.type.property xxx links to Identifier
    sym"@lsp.type.variable"                                       { Identifier }, -- @lsp.type.variable xxx links to Identifier
    NvimIdentifier                                                { Identifier }, -- NvimIdentifier xxx links to Identifier
    CocSemDecorator                                               { Identifier }, -- CocSemDecorator xxx links to Identifier
    CocSemStruct                                                  { Identifier }, -- CocSemStruct   xxx links to Identifier
    Conditional                                                   { fg="#848586", }, -- Conditional    xxx guifg=#848586
    sym"@conditional"                                             { Conditional }, -- @conditional   xxx links to Conditional
    Statement                                                     { gui="bold", fg="#848586", }, -- Statement      xxx ctermfg=11 gui=bold guifg=#848586
    Repeat                                                        { Statement }, -- Repeat         xxx links to Statement
    Exception                                                     { Statement }, -- Exception      xxx links to Statement
    Label                                                         { fg="#fbfbfb", }, -- Label          xxx guifg=#fbfbfb
    sym"@label"                                                   { Label }, -- @label         xxx links to Label
    Operator                                                      { fg="#848586", }, -- Operator       xxx guifg=#848586
    sym"@operator"                                                { Operator }, -- @operator      xxx links to Operator
    NvimAssignment                                                { Operator }, -- NvimAssignment xxx links to Operator
    NvimOperator                                                  { Operator }, -- NvimOperator   xxx links to Operator
    Keyword                                                       { gui="bold", fg="#848586", }, -- Keyword        xxx gui=bold guifg=#848586
    sym"@keyword"                                                 { Keyword }, -- @keyword       xxx links to Keyword
    PreProc                                                       { fg="#848586", }, -- PreProc        xxx ctermfg=81 guifg=#848586
    Include                                                       { PreProc }, -- Include        xxx links to PreProc
    Macro                                                         { PreProc }, -- Macro          xxx links to PreProc
    PreCondit                                                     { PreProc }, -- PreCondit      xxx links to PreProc
    sym"@preproc"                                                 { PreProc }, -- @preproc       xxx links to PreProc
    Define                                                        { fg="#848586", }, -- Define         xxx guifg=#848586
    sym"@constant.macro"                                          { Define }, -- @constant.macro xxx links to Define
    sym"@define"                                                  { Define }, -- @define        xxx links to Define
    StorageClass                                                  { gui="italic", fg="#d4d4d4", }, -- StorageClass   xxx gui=italic guifg=#d4d4d4
    sym"@storageclass"                                            { StorageClass }, -- @storageclass  xxx links to StorageClass
    Type                                                          { gui="bold", fg="#d4d4d4", }, -- Type           xxx ctermfg=121 gui=bold guifg=#d4d4d4
    Structure                                                     { Type }, -- Structure      xxx links to Type
    Typedef                                                       { Type }, -- Typedef        xxx links to Type
    sym"@type"                                                    { Type }, -- @type          xxx links to Type
    sym"@lsp.type.type"                                           { Type }, -- @lsp.type.type xxx links to Type
    NvimNumberPrefix                                              { Type }, -- NvimNumberPrefix xxx links to Type
    NvimOptionSigil                                               { Type }, -- NvimOptionSigil xxx links to Type
    Tag                                                           { fg="#848586", }, -- Tag            xxx guifg=#848586
    sym"@tag"                                                     { Tag }, -- @tag           xxx links to Tag
    Special                                                       { fg="#fbfbfb", }, -- Special        xxx ctermfg=224 guifg=#fbfbfb
    SpecialChar                                                   { Special }, -- SpecialChar    xxx links to Special
    Delimiter                                                     { Special }, -- Delimiter      xxx links to Special
    SpecialComment                                                { Special }, -- SpecialComment xxx links to Special
    Debug                                                         { Special }, -- Debug          xxx links to Special
    sym"@constant.builtin"                                        { Special }, -- @constant.builtin xxx links to Special
    sym"@function.builtin"                                        { Special }, -- @function.builtin xxx links to Special
    sym"@constructor"                                             { Special }, -- @constructor   xxx links to Special
    DiagnosticError                                               { fg="red", }, -- DiagnosticError xxx ctermfg=1 guifg=Red
    DiagnosticVirtualTextError                                    { DiagnosticError }, -- DiagnosticVirtualTextError xxx links to DiagnosticError
    DiagnosticFloatingError                                       { DiagnosticError }, -- DiagnosticFloatingError xxx links to DiagnosticError
    DiagnosticSignError                                           { DiagnosticError }, -- DiagnosticSignError xxx links to DiagnosticError
    CocErrorFloat                                                 { DiagnosticError }, -- CocErrorFloat  xxx links to DiagnosticError
    DiagnosticWarn                                                { fg="orange", }, -- DiagnosticWarn xxx ctermfg=3 guifg=Orange
    DiagnosticVirtualTextWarn                                     { DiagnosticWarn }, -- DiagnosticVirtualTextWarn xxx links to DiagnosticWarn
    DiagnosticFloatingWarn                                        { DiagnosticWarn }, -- DiagnosticFloatingWarn xxx links to DiagnosticWarn
    DiagnosticSignWarn                                            { DiagnosticWarn }, -- DiagnosticSignWarn xxx links to DiagnosticWarn
    CocWarningFloat                                               { DiagnosticWarn }, -- CocWarningFloat xxx links to DiagnosticWarn
    DiagnosticInfo                                                { fg="lightblue", }, -- DiagnosticInfo xxx ctermfg=4 guifg=LightBlue
    DiagnosticVirtualTextInfo                                     { DiagnosticInfo }, -- DiagnosticVirtualTextInfo xxx links to DiagnosticInfo
    DiagnosticFloatingInfo                                        { DiagnosticInfo }, -- DiagnosticFloatingInfo xxx links to DiagnosticInfo
    DiagnosticSignInfo                                            { DiagnosticInfo }, -- DiagnosticSignInfo xxx links to DiagnosticInfo
    CocInfoFloat                                                  { DiagnosticInfo }, -- CocInfoFloat   xxx links to DiagnosticInfo
    DiagnosticHint                                                { fg="lightgrey", }, -- DiagnosticHint xxx ctermfg=7 guifg=LightGrey
    DiagnosticVirtualTextHint                                     { DiagnosticHint }, -- DiagnosticVirtualTextHint xxx links to DiagnosticHint
    DiagnosticFloatingHint                                        { DiagnosticHint }, -- DiagnosticFloatingHint xxx links to DiagnosticHint
    DiagnosticSignHint                                            { DiagnosticHint }, -- DiagnosticSignHint xxx links to DiagnosticHint
    CocHintFloat                                                  { DiagnosticHint }, -- CocHintFloat   xxx links to DiagnosticHint
    DiagnosticOk                                                  { fg="lightgreen", }, -- DiagnosticOk   xxx ctermfg=10 guifg=LightGreen
    DiagnosticVirtualTextOk                                       { DiagnosticOk }, -- DiagnosticVirtualTextOk xxx links to DiagnosticOk
    DiagnosticFloatingOk                                          { DiagnosticOk }, -- DiagnosticFloatingOk xxx links to DiagnosticOk
    DiagnosticSignOk                                              { DiagnosticOk }, -- DiagnosticSignOk xxx links to DiagnosticOk
    DiagnosticUnderlineError                                      { gui="underline", sp="red", }, -- DiagnosticUnderlineError xxx cterm=underline gui=underline guisp=Red
    CocErrorHighlight                                             { DiagnosticUnderlineError }, -- CocErrorHighlight xxx links to DiagnosticUnderlineError
    DiagnosticUnderlineWarn                                       { gui="underline", sp="orange", }, -- DiagnosticUnderlineWarn xxx cterm=underline gui=underline guisp=Orange
    CocWarningHighlight                                           { DiagnosticUnderlineWarn }, -- CocWarningHighlight xxx links to DiagnosticUnderlineWarn
    DiagnosticUnderlineInfo                                       { gui="underline", sp="lightblue", }, -- DiagnosticUnderlineInfo xxx cterm=underline gui=underline guisp=LightBlue
    CocInfoHighlight                                              { DiagnosticUnderlineInfo }, -- CocInfoHighlight xxx links to DiagnosticUnderlineInfo
    DiagnosticUnderlineHint                                       { gui="underline", sp="lightgrey", }, -- DiagnosticUnderlineHint xxx cterm=underline gui=underline guisp=LightGrey
    CocHintHighlight                                              { DiagnosticUnderlineHint }, -- CocHintHighlight xxx links to DiagnosticUnderlineHint
    DiagnosticUnderlineOk                                         { gui="underline", sp="lightgreen", }, -- DiagnosticUnderlineOk xxx cterm=underline gui=underline guisp=LightGreen
    DiagnosticDeprecated                                          { gui="strikethrough", sp="red", }, -- DiagnosticDeprecated xxx cterm=strikethrough gui=strikethrough guisp=Red
    Comment                                                       { fg="#484848", }, -- Comment        xxx ctermfg=14 guifg=#484848
    DiagnosticUnnecessary                                         { Comment }, -- DiagnosticUnnecessary xxx links to Comment
    sym"@text.literal"                                            { Comment }, -- @text.literal  xxx links to Comment
    sym"@comment"                                                 { Comment }, -- @comment       xxx links to Comment
    sym"@lsp.type.comment"                                        { Comment }, -- @lsp.type.comment xxx links to Comment
    CocListPath                                                   { Comment }, -- CocListPath    xxx links to Comment
    CocTreeDescription                                            { Comment }, -- CocTreeDescription xxx links to Comment
    CocPumDetail                                                  { Comment }, -- CocPumDetail   xxx links to Comment
    CocPumShortcut                                                { Comment }, -- CocPumShortcut xxx links to Comment
    Underlined                                                    { gui="underline", fg="#80a0ff", }, -- Underlined     xxx cterm=underline ctermfg=81 gui=underline guifg=#80a0ff
    sym"@text.uri"                                                { Underlined }, -- @text.uri      xxx links to Underlined
    sym"@text.underline"                                          { Underlined }, -- @text.underline xxx links to Underlined
    MatchParen                                                    { gui="underline", bg="darkcyan", fg="#ff8800", }, -- MatchParen     xxx ctermbg=6 gui=underline guifg=#ff8800 guibg=DarkCyan
    Ignore                                                        { fg="bg", }, -- Ignore         xxx ctermfg=0 guifg=bg
    NvimInternalError                                             { bg="red", fg="red", }, -- NvimInternalError xxx ctermfg=9 ctermbg=9 guifg=Red guibg=Red
    NvimFigureBrace                                               { NvimInternalError }, -- NvimFigureBrace xxx links to NvimInternalError
    NvimSingleQuotedUnknownEscape                                 { NvimInternalError }, -- NvimSingleQuotedUnknownEscape xxx links to NvimInternalError
    NvimInvalidSingleQuotedUnknownEscape                          { NvimInternalError }, -- NvimInvalidSingleQuotedUnknownEscape xxx links to NvimInternalError
    rubyAttribute                                                 { fg="#c00123", }, -- rubyAttribute  xxx guifg=#c00123
    rubyLocalVariableOrMethod                                     { fg="#fbfbfb", }, -- rubyLocalVariableOrMethod xxx guifg=#fbfbfb
    rubyGlobalVariable                                            { gui="italic", fg="#fbfbfb", }, -- rubyGlobalVariable xxx gui=italic guifg=#fbfbfb
    rubyInstanceVariable                                          { fg="#fbfbfb", }, -- rubyInstanceVariable xxx guifg=#fbfbfb
    rubyKeyword                                                   { fg="#848586", }, -- rubyKeyword    xxx guifg=#848586
    rubyKeywordAsMethod                                           { gui="bold", fg="#848586", }, -- rubyKeywordAsMethod xxx gui=bold guifg=#848586
    rubyClassDeclaration                                          { gui="bold", fg="#848586", }, -- rubyClassDeclaration xxx gui=bold guifg=#848586
    rubyClass                                                     { gui="bold", fg="#848586", }, -- rubyClass      xxx gui=bold guifg=#848586
    rubyNumber                                                    { fg="#d4d4d4", }, -- rubyNumber     xxx guifg=#d4d4d4
    pythonBuiltinFunc                                             { fg="#c00123", }, -- pythonBuiltinFunc xxx guifg=#c00123
    goBuiltins                                                    { fg="#c00123", }, -- goBuiltins     xxx guifg=#c00123
    jsBuiltins                                                    { fg="#c00123", }, -- jsBuiltins     xxx guifg=#c00123
    jsFunction                                                    { gui="bold", fg="#848586", }, -- jsFunction     xxx gui=bold guifg=#848586
    jsGlobalObjects                                               { fg="#d4d4d4", }, -- jsGlobalObjects xxx guifg=#d4d4d4
    jsAssignmentExps                                              { fg="#fbfbfb", }, -- jsAssignmentExps xxx guifg=#fbfbfb
    htmlLink                                                      { gui="underline", fg="#fbfbfb", }, -- htmlLink       xxx gui=underline guifg=#fbfbfb
    htmlStatement                                                 { fg="#848586", }, -- htmlStatement  xxx guifg=#848586
    htmlSpecialTagName                                            { fg="#848586", }, -- htmlSpecialTagName xxx guifg=#848586
    mkdCode                                                       { fg="#c00123", }, -- mkdCode        xxx guifg=#c00123
    sym"@neorg.markup.verbatim"                                   { fg="#c8c8c8", }, -- @neorg.markup.verbatim xxx guifg=#c8c8c8
    sym"@neorg.markup.inline_comment"                             { fg="#969696", }, -- @neorg.markup.inline_comment xxx guifg=#969696
    sym"@neorg.markup.underline"                                  { gui="underline", }, -- @neorg.markup.underline xxx cterm=underline gui=underline
    sym"@neorg.markup.strikethrough"                              { gui="strikethrough", }, -- @neorg.markup.strikethrough xxx cterm=strikethrough gui=strikethrough
    sym"@neorg.tags.ranged_verbatim.code_block"                   { bg="#000000", }, -- @neorg.tags.ranged_verbatim.code_block xxx guibg=#000000
    CocMenuSel                                                    { bg="#292929", }, -- CocMenuSel     xxx ctermbg=0 guibg=#292929
    CocListLine                                                   { bg="#141414", }, -- CocListLine    xxx ctermbg=232 guibg=#141414
    CocSelectedText                                               { fg="#fb4934", }, -- CocSelectedText xxx ctermfg=9 guifg=#fb4934
    CocCodeLens                                                   { fg="#999999", }, -- CocCodeLens    xxx ctermfg=248 guifg=#999999
    CocUnderline                                                  { gui="underline", sp="#ebdbb2", }, -- CocUnderline   xxx cterm=underline gui=underline guisp=#ebdbb2
    CocNotificationButton                                         { CocUnderline }, -- CocNotificationButton xxx links to CocUnderline
    CocBold                                                       { gui="bold", }, -- CocBold        xxx cterm=bold gui=bold
    CocTreeOpenClose                                              { CocBold }, -- CocTreeOpenClose xxx links to CocBold
    CocItalic                                                     { gui="italic", }, -- CocItalic      xxx cterm=italic gui=italic
    CocStrikeThrough                                              { gui="strikethrough", }, -- CocStrikeThrough xxx cterm=strikethrough gui=strikethrough
    CocDeprecatedHighlight                                        { CocStrikeThrough }, -- CocDeprecatedHighlight xxx links to CocStrikeThrough
    CocPumDeprecated                                              { CocStrikeThrough }, -- CocPumDeprecated xxx links to CocStrikeThrough
    CocMarkdownLink                                               { fg="#15aabf", }, -- CocMarkdownLink xxx ctermfg=12 guifg=#15aabf
    CocDisabled                                                   { fg="#999999", }, -- CocDisabled    xxx ctermfg=248 guifg=#999999
    CocSearch                                                     { fg="#15aabf", }, -- CocSearch      xxx ctermfg=12 guifg=#15aabf
    CocFloatActive                                                { CocSearch }, -- CocFloatActive xxx links to CocSearch
    CocListSearch                                                 { CocSearch }, -- CocListSearch  xxx links to CocSearch
    CocPumSearch                                                  { CocSearch }, -- CocPumSearch   xxx links to CocSearch
    CocLink                                                       { gui="underline", sp="#15aabf", }, -- CocLink        xxx cterm=underline gui=underline guisp=#15aabf
    CocNotificationProgress                                       { fg="#15aabf", }, -- CocNotificationProgress xxx ctermfg=12 guifg=#15aabf
    CocVirtualText                                                { fg="#504945", }, -- CocVirtualText xxx ctermfg=12 guifg=#504945
    CocPumVirtualText                                             { CocVirtualText }, -- CocPumVirtualText xxx links to CocVirtualText
    CocInputBoxVirtualText                                        { CocVirtualText }, -- CocInputBoxVirtualText xxx links to CocVirtualText
    CocFloatDividingLine                                          { CocVirtualText }, -- CocFloatDividingLine xxx links to CocVirtualText
    CocCursorTransparent                                          { gui="strikethrough", blend=100, }, -- CocCursorTransparent xxx gui=strikethrough blend=100
    CocInlayHint                                                  { bg="#141414", fg="lightgrey", }, -- CocInlayHint   xxx ctermfg=7 ctermbg=232 guifg=LightGrey guibg=#141414
    CocInlayHintParameter                                         { CocInlayHint }, -- CocInlayHintParameter xxx links to CocInlayHint
    CocInlayHintType                                              { CocInlayHint }, -- CocInlayHintType xxx links to CocInlayHint
    CocListBlackBlack                                             { bg="#000000", fg="#000000", }, -- CocListBlackBlack xxx guifg=#000000 guibg=#000000
    CocListBlackBlue                                              { bg="#fbfbfb", fg="#000000", }, -- CocListBlackBlue xxx guifg=#000000 guibg=#fbfbfb
    CocListBlackGreen                                             { bg="#848586", fg="#000000", }, -- CocListBlackGreen xxx guifg=#000000 guibg=#848586
    CocListBlackGrey                                              { bg="#141414", fg="#000000", }, -- CocListBlackGrey xxx guifg=#000000 guibg=#141414
    CocListBlackWhite                                             { bg="#484848", fg="#000000", }, -- CocListBlackWhite xxx guifg=#000000 guibg=#484848
    CocListBlackCyan                                              { bg="#d3d3d3", fg="#000000", }, -- CocListBlackCyan xxx guifg=#000000 guibg=#d3d3d3
    CocListBlackYellow                                            { bg="#3d3d3d", fg="#000000", }, -- CocListBlackYellow xxx guifg=#000000 guibg=#3d3d3d
    CocListBlackMagenta                                           { bg="#c00123", fg="#000000", }, -- CocListBlackMagenta xxx guifg=#000000 guibg=#c00123
    CocListBlackRed                                               { bg="#ff0000", fg="#000000", }, -- CocListBlackRed xxx guifg=#000000 guibg=#ff0000
    CocListFgBlack                                                { fg="#000000", }, -- CocListFgBlack xxx ctermfg=0 guifg=#000000
    CocListBgBlack                                                { bg="#000000", }, -- CocListBgBlack xxx ctermbg=0 guibg=#000000
    CocListBlueBlack                                              { bg="#000000", fg="#fbfbfb", }, -- CocListBlueBlack xxx guifg=#fbfbfb guibg=#000000
    CocListBlueBlue                                               { bg="#fbfbfb", fg="#fbfbfb", }, -- CocListBlueBlue xxx guifg=#fbfbfb guibg=#fbfbfb
    CocListBlueGreen                                              { bg="#848586", fg="#fbfbfb", }, -- CocListBlueGreen xxx guifg=#fbfbfb guibg=#848586
    CocListBlueGrey                                               { bg="#141414", fg="#fbfbfb", }, -- CocListBlueGrey xxx guifg=#fbfbfb guibg=#141414
    CocListBlueWhite                                              { bg="#484848", fg="#fbfbfb", }, -- CocListBlueWhite xxx guifg=#fbfbfb guibg=#484848
    CocListBlueCyan                                               { bg="#d3d3d3", fg="#fbfbfb", }, -- CocListBlueCyan xxx guifg=#fbfbfb guibg=#d3d3d3
    CocListBlueYellow                                             { bg="#3d3d3d", fg="#fbfbfb", }, -- CocListBlueYellow xxx guifg=#fbfbfb guibg=#3d3d3d
    CocListBlueMagenta                                            { bg="#c00123", fg="#fbfbfb", }, -- CocListBlueMagenta xxx guifg=#fbfbfb guibg=#c00123
    CocListBlueRed                                                { bg="#ff0000", fg="#fbfbfb", }, -- CocListBlueRed xxx guifg=#fbfbfb guibg=#ff0000
    CocListFgBlue                                                 { fg="#fbfbfb", }, -- CocListFgBlue  xxx ctermfg=12 guifg=#fbfbfb
    CocListBgBlue                                                 { bg="#fbfbfb", }, -- CocListBgBlue  xxx ctermbg=12 guibg=#fbfbfb
    CocListGreenBlack                                             { bg="#000000", fg="#848586", }, -- CocListGreenBlack xxx guifg=#848586 guibg=#000000
    CocListGreenBlue                                              { bg="#fbfbfb", fg="#848586", }, -- CocListGreenBlue xxx guifg=#848586 guibg=#fbfbfb
    CocListGreenGreen                                             { bg="#848586", fg="#848586", }, -- CocListGreenGreen xxx guifg=#848586 guibg=#848586
    CocListGreenGrey                                              { bg="#141414", fg="#848586", }, -- CocListGreenGrey xxx guifg=#848586 guibg=#141414
    CocListGreenWhite                                             { bg="#484848", fg="#848586", }, -- CocListGreenWhite xxx guifg=#848586 guibg=#484848
    CocListGreenCyan                                              { bg="#d3d3d3", fg="#848586", }, -- CocListGreenCyan xxx guifg=#848586 guibg=#d3d3d3
    CocListGreenYellow                                            { bg="#3d3d3d", fg="#848586", }, -- CocListGreenYellow xxx guifg=#848586 guibg=#3d3d3d
    CocListGreenMagenta                                           { bg="#c00123", fg="#848586", }, -- CocListGreenMagenta xxx guifg=#848586 guibg=#c00123
    CocListGreenRed                                               { bg="#ff0000", fg="#848586", }, -- CocListGreenRed xxx guifg=#848586 guibg=#ff0000
    CocListFgGreen                                                { fg="#848586", }, -- CocListFgGreen xxx ctermfg=10 guifg=#848586
    CocListBgGreen                                                { bg="#848586", }, -- CocListBgGreen xxx ctermbg=10 guibg=#848586
    CocListGreyBlack                                              { bg="#000000", fg="#141414", }, -- CocListGreyBlack xxx guifg=#141414 guibg=#000000
    CocListGreyBlue                                               { bg="#fbfbfb", fg="#141414", }, -- CocListGreyBlue xxx guifg=#141414 guibg=#fbfbfb
    CocListGreyGreen                                              { bg="#848586", fg="#141414", }, -- CocListGreyGreen xxx guifg=#141414 guibg=#848586
    CocListGreyGrey                                               { bg="#141414", fg="#141414", }, -- CocListGreyGrey xxx guifg=#141414 guibg=#141414
    CocListGreyWhite                                              { bg="#484848", fg="#141414", }, -- CocListGreyWhite xxx guifg=#141414 guibg=#484848
    CocListGreyCyan                                               { bg="#d3d3d3", fg="#141414", }, -- CocListGreyCyan xxx guifg=#141414 guibg=#d3d3d3
    CocListGreyYellow                                             { bg="#3d3d3d", fg="#141414", }, -- CocListGreyYellow xxx guifg=#141414 guibg=#3d3d3d
    CocListGreyMagenta                                            { bg="#c00123", fg="#141414", }, -- CocListGreyMagenta xxx guifg=#141414 guibg=#c00123
    CocListGreyRed                                                { bg="#ff0000", fg="#141414", }, -- CocListGreyRed xxx guifg=#141414 guibg=#ff0000
    CocListFgGrey                                                 { fg="#141414", }, -- CocListFgGrey  xxx ctermfg=248 guifg=#141414
    CocListBgGrey                                                 { bg="#141414", }, -- CocListBgGrey  xxx ctermbg=248 guibg=#141414
    CocListWhiteBlack                                             { bg="#000000", fg="#484848", }, -- CocListWhiteBlack xxx guifg=#484848 guibg=#000000
    CocListWhiteBlue                                              { bg="#fbfbfb", fg="#484848", }, -- CocListWhiteBlue xxx guifg=#484848 guibg=#fbfbfb
    CocListWhiteGreen                                             { bg="#848586", fg="#484848", }, -- CocListWhiteGreen xxx guifg=#484848 guibg=#848586
    CocListWhiteGrey                                              { bg="#141414", fg="#484848", }, -- CocListWhiteGrey xxx guifg=#484848 guibg=#141414
    CocListWhiteWhite                                             { bg="#484848", fg="#484848", }, -- CocListWhiteWhite xxx guifg=#484848 guibg=#484848
    CocListWhiteCyan                                              { bg="#d3d3d3", fg="#484848", }, -- CocListWhiteCyan xxx guifg=#484848 guibg=#d3d3d3
    CocListWhiteYellow                                            { bg="#3d3d3d", fg="#484848", }, -- CocListWhiteYellow xxx guifg=#484848 guibg=#3d3d3d
    CocListWhiteMagenta                                           { bg="#c00123", fg="#484848", }, -- CocListWhiteMagenta xxx guifg=#484848 guibg=#c00123
    CocListWhiteRed                                               { bg="#ff0000", fg="#484848", }, -- CocListWhiteRed xxx guifg=#484848 guibg=#ff0000
    CocListFgWhite                                                { fg="#484848", }, -- CocListFgWhite xxx ctermfg=15 guifg=#484848
    CocListBgWhite                                                { bg="#484848", }, -- CocListBgWhite xxx ctermbg=15 guibg=#484848
    CocListCyanBlack                                              { bg="#000000", fg="#d3d3d3", }, -- CocListCyanBlack xxx guifg=#d3d3d3 guibg=#000000
    CocListCyanBlue                                               { bg="#fbfbfb", fg="#d3d3d3", }, -- CocListCyanBlue xxx guifg=#d3d3d3 guibg=#fbfbfb
    CocListCyanGreen                                              { bg="#848586", fg="#d3d3d3", }, -- CocListCyanGreen xxx guifg=#d3d3d3 guibg=#848586
    CocListCyanGrey                                               { bg="#141414", fg="#d3d3d3", }, -- CocListCyanGrey xxx guifg=#d3d3d3 guibg=#141414
    CocListCyanWhite                                              { bg="#484848", fg="#d3d3d3", }, -- CocListCyanWhite xxx guifg=#d3d3d3 guibg=#484848
    CocListCyanCyan                                               { bg="#d3d3d3", fg="#d3d3d3", }, -- CocListCyanCyan xxx guifg=#d3d3d3 guibg=#d3d3d3
    CocListCyanYellow                                             { bg="#3d3d3d", fg="#d3d3d3", }, -- CocListCyanYellow xxx guifg=#d3d3d3 guibg=#3d3d3d
    CocListCyanMagenta                                            { bg="#c00123", fg="#d3d3d3", }, -- CocListCyanMagenta xxx guifg=#d3d3d3 guibg=#c00123
    CocListCyanRed                                                { bg="#ff0000", fg="#d3d3d3", }, -- CocListCyanRed xxx guifg=#d3d3d3 guibg=#ff0000
    CocListFgCyan                                                 { fg="#d3d3d3", }, -- CocListFgCyan  xxx ctermfg=14 guifg=#d3d3d3
    CocListBgCyan                                                 { bg="#d3d3d3", }, -- CocListBgCyan  xxx ctermbg=14 guibg=#d3d3d3
    CocListYellowBlack                                            { bg="#000000", fg="#3d3d3d", }, -- CocListYellowBlack xxx guifg=#3d3d3d guibg=#000000
    CocListYellowBlue                                             { bg="#fbfbfb", fg="#3d3d3d", }, -- CocListYellowBlue xxx guifg=#3d3d3d guibg=#fbfbfb
    CocListYellowGreen                                            { bg="#848586", fg="#3d3d3d", }, -- CocListYellowGreen xxx guifg=#3d3d3d guibg=#848586
    CocListYellowGrey                                             { bg="#141414", fg="#3d3d3d", }, -- CocListYellowGrey xxx guifg=#3d3d3d guibg=#141414
    CocListYellowWhite                                            { bg="#484848", fg="#3d3d3d", }, -- CocListYellowWhite xxx guifg=#3d3d3d guibg=#484848
    CocListYellowCyan                                             { bg="#d3d3d3", fg="#3d3d3d", }, -- CocListYellowCyan xxx guifg=#3d3d3d guibg=#d3d3d3
    CocListYellowYellow                                           { bg="#3d3d3d", fg="#3d3d3d", }, -- CocListYellowYellow xxx guifg=#3d3d3d guibg=#3d3d3d
    CocListYellowMagenta                                          { bg="#c00123", fg="#3d3d3d", }, -- CocListYellowMagenta xxx guifg=#3d3d3d guibg=#c00123
    CocListYellowRed                                              { bg="#ff0000", fg="#3d3d3d", }, -- CocListYellowRed xxx guifg=#3d3d3d guibg=#ff0000
    CocListFgYellow                                               { fg="#3d3d3d", }, -- CocListFgYellow xxx ctermfg=11 guifg=#3d3d3d
    CocListBgYellow                                               { bg="#3d3d3d", }, -- CocListBgYellow xxx ctermbg=11 guibg=#3d3d3d
    CocListMagentaBlack                                           { bg="#000000", fg="#c00123", }, -- CocListMagentaBlack xxx guifg=#c00123 guibg=#000000
    CocListMagentaBlue                                            { bg="#fbfbfb", fg="#c00123", }, -- CocListMagentaBlue xxx guifg=#c00123 guibg=#fbfbfb
    CocListMagentaGreen                                           { bg="#848586", fg="#c00123", }, -- CocListMagentaGreen xxx guifg=#c00123 guibg=#848586
    CocListMagentaGrey                                            { bg="#141414", fg="#c00123", }, -- CocListMagentaGrey xxx guifg=#c00123 guibg=#141414
    CocListMagentaWhite                                           { bg="#484848", fg="#c00123", }, -- CocListMagentaWhite xxx guifg=#c00123 guibg=#484848
    CocListMagentaCyan                                            { bg="#d3d3d3", fg="#c00123", }, -- CocListMagentaCyan xxx guifg=#c00123 guibg=#d3d3d3
    CocListMagentaYellow                                          { bg="#3d3d3d", fg="#c00123", }, -- CocListMagentaYellow xxx guifg=#c00123 guibg=#3d3d3d
    CocListMagentaMagenta                                         { bg="#c00123", fg="#c00123", }, -- CocListMagentaMagenta xxx guifg=#c00123 guibg=#c00123
    CocListMagentaRed                                             { bg="#ff0000", fg="#c00123", }, -- CocListMagentaRed xxx guifg=#c00123 guibg=#ff0000
    CocListFgMagenta                                              { fg="#c00123", }, -- CocListFgMagenta xxx ctermfg=13 guifg=#c00123
    CocListBgMagenta                                              { bg="#c00123", }, -- CocListBgMagenta xxx ctermbg=13 guibg=#c00123
    CocListRedBlack                                               { bg="#000000", fg="#ff0000", }, -- CocListRedBlack xxx guifg=#ff0000 guibg=#000000
    CocListRedBlue                                                { bg="#fbfbfb", fg="#ff0000", }, -- CocListRedBlue xxx guifg=#ff0000 guibg=#fbfbfb
    CocListRedGreen                                               { bg="#848586", fg="#ff0000", }, -- CocListRedGreen xxx guifg=#ff0000 guibg=#848586
    CocListRedGrey                                                { bg="#141414", fg="#ff0000", }, -- CocListRedGrey xxx guifg=#ff0000 guibg=#141414
    CocListRedWhite                                               { bg="#484848", fg="#ff0000", }, -- CocListRedWhite xxx guifg=#ff0000 guibg=#484848
    CocListRedCyan                                                { bg="#d3d3d3", fg="#ff0000", }, -- CocListRedCyan xxx guifg=#ff0000 guibg=#d3d3d3
    CocListRedYellow                                              { bg="#3d3d3d", fg="#ff0000", }, -- CocListRedYellow xxx guifg=#ff0000 guibg=#3d3d3d
    CocListRedMagenta                                             { bg="#c00123", fg="#ff0000", }, -- CocListRedMagenta xxx guifg=#ff0000 guibg=#c00123
    CocListRedRed                                                 { bg="#ff0000", fg="#ff0000", }, -- CocListRedRed  xxx guifg=#ff0000 guibg=#ff0000
    CocListFgRed                                                  { fg="#ff0000", }, -- CocListFgRed   xxx ctermfg=9 guifg=#ff0000
    CocListBgRed                                                  { bg="#ff0000", }, -- CocListBgRed   xxx ctermbg=9 guibg=#ff0000
    CocSymbolUnit                                                 { fg="seagreen", }, -- CocSymbolUnit  xxx ctermfg=121 guifg=SeaGreen
    CocSymbolNumber                                               { fg="#d4d4d4", }, -- CocSymbolNumber xxx ctermfg=223 guifg=#d4d4d4
    CocSymbolFunction                                             { fg="#fbfbfb", }, -- CocSymbolFunction xxx ctermfg=223 guifg=#fbfbfb
    CocSymbolKey                                                  { fg="#d4d4d4", }, -- CocSymbolKey   xxx ctermfg=14 guifg=#d4d4d4
    CocSymbolKeyword                                              { fg="#848586", }, -- CocSymbolKeyword xxx ctermfg=223 guifg=#848586
    CocSymbolReference                                            { fg="#d4d4d4", }, -- CocSymbolReference xxx ctermfg=14 guifg=#d4d4d4
    CocSymbolFolder                                               { fg="seagreen", }, -- CocSymbolFolder xxx ctermfg=121 guifg=SeaGreen
    CocSymbolVariable                                             { fg="#d4d4d4", }, -- CocSymbolVariable xxx ctermfg=14 guifg=#d4d4d4
    CocSymbolNull                                                 { fg="#d4d4d4", }, -- CocSymbolNull  xxx ctermfg=121 guifg=#d4d4d4
    CocSymbolValue                                                { fg="seagreen", }, -- CocSymbolValue xxx ctermfg=121 guifg=SeaGreen
    CocSymbolConstant                                             { fg="#d4d4d4", }, -- CocSymbolConstant xxx ctermfg=13 guifg=#d4d4d4
    CocSymbolText                                                 { fg="seagreen", }, -- CocSymbolText  xxx ctermfg=121 guifg=SeaGreen
    CocSymbolModule                                               { fg="#848586", }, -- CocSymbolModule xxx ctermfg=11 guifg=#848586
    CocSymbolPackage                                              { fg="#848586", }, -- CocSymbolPackage xxx ctermfg=11 guifg=#848586
    CocSymbolClass                                                { fg="#fbfbfb", }, -- CocSymbolClass xxx ctermfg=224 guifg=#fbfbfb
    CocSymbolOperator                                             { fg="#848586", }, -- CocSymbolOperator xxx ctermfg=223 guifg=#848586
    CocSymbolStruct                                               { fg="#848586", }, -- CocSymbolStruct xxx ctermfg=223 guifg=#848586
    CocSymbolObject                                               { fg="seagreen", }, -- CocSymbolObject xxx ctermfg=121 guifg=SeaGreen
    CocSymbolMethod                                               { fg="#fbfbfb", }, -- CocSymbolMethod xxx ctermfg=223 guifg=#fbfbfb
    CocSymbolArray                                                { fg="seagreen", }, -- CocSymbolArray xxx ctermfg=121 guifg=SeaGreen
    CocSymbolEnum                                                 { fg="#d4d4d4", }, -- CocSymbolEnum  xxx ctermfg=121 guifg=#d4d4d4
    CocSymbolField                                                { fg="#d4d4d4", }, -- CocSymbolField xxx ctermfg=14 guifg=#d4d4d4
    CocSymbolInterface                                            { fg="#d4d4d4", }, -- CocSymbolInterface xxx ctermfg=121 guifg=#d4d4d4
    CocSymbolProperty                                             { fg="#d4d4d4", }, -- CocSymbolProperty xxx ctermfg=14 guifg=#d4d4d4
    CocSymbolColor                                                { fg="#d4d4d4", }, -- CocSymbolColor xxx ctermfg=223 guifg=#d4d4d4
    CocSymbolFile                                                 { fg="#848586", }, -- CocSymbolFile  xxx ctermfg=11 guifg=#848586
    CocSymbolEvent                                                { fg="#d4d4d4", }, -- CocSymbolEvent xxx ctermfg=13 guifg=#d4d4d4
    CocSymbolTypeParameter                                        { fg="#d4d4d4", }, -- CocSymbolTypeParameter xxx ctermfg=14 guifg=#d4d4d4
    CocSymbolConstructor                                          { fg="#fbfbfb", }, -- CocSymbolConstructor xxx ctermfg=224 guifg=#fbfbfb
    CocSymbolSnippet                                              { fg="seagreen", }, -- CocSymbolSnippet xxx ctermfg=121 guifg=SeaGreen
    CocSymbolBoolean                                              { fg="#d4d4d4", }, -- CocSymbolBoolean xxx ctermfg=223 guifg=#d4d4d4
    CocSymbolNamespace                                            { fg="#d4d4d4", }, -- CocSymbolNamespace xxx ctermfg=14 guifg=#d4d4d4
    CocSymbolString                                               { fg="#484848", }, -- CocSymbolString xxx ctermfg=223 guifg=#484848
    CocSymbolEnumMember                                           { fg="#d4d4d4", }, -- CocSymbolEnumMember xxx ctermfg=14 guifg=#d4d4d4
  }
end)
return theme
