-- autogenerated lush spec on Sun 01 Oct 2023 05:58:10 PM EDT
-- Run :Lushify
-- then /Normal to find the Normal group and edit your fg & bg colors
    -- colors/colorscheme.lua

local colors = {
-- content here will not be touched
-- PATCH_OPEN
-- group data will be inserted here
-- PATCH_CLOSE
-- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='farin'")

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end

local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv
local theme = lush(function(injected_functions)
    local dark_gray  = hsl("#1e1e1e")
    local wolken = hsl("#444444")
    local selection_foreground = hsl("#1e1e1e")
    local selection_background = hsl("#aaaaaa")
    local url_color  = hsl("#657b83")
    local color0     = hsl("#444444")
    local color8     = hsl("#666666")
    local pink_cherry = hsl("#ff1155")
    local pink_fruit     = hsl("#ff4488")
    local vividgreen     = hsl("#11ff55")
    local color10    = hsl("#44ff88")
    local orangey     = hsl("#ffbb33")
    local paleorange    = hsl("#ffdd66")
    local blau     = hsl("#1155ff")
    local paleblau    = hsl("#4488ff")
    local palepink     = hsl("#ed53c9")
    local softpink    = hsl("#dd66ff")
    local cyano     = hsl("#00ffbb")
    local palecyan    = hsl("#66ffdd")
    local color7     = hsl("#cccccc")
    local bright    = hsl("#ffffff")
    local dark       = hsl("#0e0e0e")
    local dark2      = hsl("#8e8e8e")
  local sym = injected_functions.sym
  return {

    Normal                                                      { bg=dark, fg=bright, },
    SpecialKey                                                  { fg=cyano, }, -- SpecialKey     xxx ctermfg=81 guifg=Cyan
    TermCursor                                                  { gui="reverse", }, -- TermCursor     xxx cterm=reverse gui=reverse
    NonText                                                     { gui="bold", fg=wolken, bg="#1e1e1e", }, -- NonText        xxx ctermfg=12 gui=bold guifg=#ff4488 guibg=#1e1e1e
    Whitespace                                                  { NonText }, -- Whitespace     xxx links to NonText
    LspInlayHint                                                { NonText }, -- LspInlayHint   xxx links to NonText
    Directory                                                   { fg="#ffdd66", }, -- Directory      xxx ctermfg=159 guifg=#ffdd66
    StartifyPath                                                { Directory }, -- StartifyPath   xxx links to Directory
    ErrorMsg                                                    { fg="#ff1155", }, -- ErrorMsg       xxx ctermfg=15 ctermbg=1 guifg=#ff1155
    NvimInvalidSpacing                                          { ErrorMsg }, -- NvimInvalidSpacing xxx links to ErrorMsg
    IncSearch                                                   { gui="reverse", fg="#ffbb33", }, -- IncSearch      xxx cterm=reverse gui=reverse guifg=#ffbb33
    Search                                                      { fg="#aaaaaa", bg=wolken, }, -- Search         xxx ctermfg=0 ctermbg=11 guifg=#aaaaaa guibg=#ff4488
    CurSearch                                                   { Search }, -- CurSearch      xxx links to Search
    QuickFixLine                                                { Search }, -- QuickFixLine   xxx links to Search
    Substitute                                                  { Search }, -- Substitute     xxx links to Search
    MoreMsg                                                     { gui="bold", fg="#ffbb33", }, -- MoreMsg        xxx ctermfg=121 gui=bold guifg=#ffbb33
    ModeMsg                                                     { gui="bold", }, -- ModeMsg        xxx cterm=bold gui=bold
    LineNr                                                      { fg=wolken, bg="#1e1e1e", }, -- LineNr         xxx ctermfg=11 guifg=#444444 guibg=#1e1e1e
    LineNrAbove                                                 { LineNr }, -- LineNrAbove    xxx links to LineNr
    LineNrBelow                                                 { LineNr }, -- LineNrBelow    xxx links to LineNr
    CursorLineNr                                                { gui="bold", fg="#ffbb33", }, -- CursorLineNr   xxx cterm=underline ctermfg=11 gui=bold guifg=#ffbb33
    Question                                                    { gui="bold", fg="green", }, -- Question       xxx ctermfg=121 gui=bold guifg=Green
    StatusLine                                                  { gui="bold", fg="#aaaaaa", bg=wolken, }, -- StatusLine     xxx cterm=bold,reverse gui=bold guifg=#aaaaaa guibg=#444444
    MsgSeparator                                                { StatusLine }, -- MsgSeparator   xxx links to StatusLine
    StatusLineNC                                                { fg="#aaaaaa", bg="#1e1e1e", }, -- StatusLineNC   xxx cterm=reverse guifg=#aaaaaa guibg=#1e1e1e
    VertSplit                                                   { fg=wolken, }, -- VertSplit      xxx guifg=#444444
    WinSeparator                                                { VertSplit }, -- WinSeparator   xxx links to VertSplit
    Title                                                       { gui="bold", fg="#aaaaaa", }, -- Title          xxx ctermfg=225 gui=bold guifg=#aaaaaa
    FloatTitle                                                  { Title }, -- FloatTitle     xxx links to Title
    LspInfoTitle                                                { Title }, -- LspInfoTitle   xxx links to Title
    StartifyHeader                                              { Title }, -- StartifyHeader xxx links to Title
    StartifyFooter                                              { Title }, -- StartifyFooter xxx links to Title
    StartifySelect                                              { Title }, -- StartifySelect xxx links to Title
    Visual                                                      { bg=wolken, }, -- Visual         xxx ctermbg=242 guibg=#444444
    WarningMsg                                                  { fg="#ff1155", }, -- WarningMsg     xxx ctermfg=224 guifg=#ff1155
    WildMenu                                                    { fg="black", bg="yellow", }, -- WildMenu       xxx ctermfg=0 ctermbg=11 guifg=Black guibg=Yellow
    Folded                                                      { fg="cyan", }, -- Folded         xxx ctermfg=14 guifg=Cyan
    FoldColumn                                                  { fg="cyan", bg="grey", }, -- FoldColumn     xxx ctermfg=14 ctermbg=242 guifg=Cyan guibg=Grey
    CursorLineFold                                              { FoldColumn }, -- CursorLineFold xxx links to FoldColumn
    DiffAdd                                                     { fg="#11ff55", }, -- DiffAdd        xxx ctermbg=4 guifg=#11ff55
    DiffChange                                                  { fg="#ffbb33", }, -- DiffChange     xxx ctermbg=5 guifg=#ffbb33
    DiffDelete                                                  { gui="bold", fg="#ff1155", }, -- DiffDelete     xxx ctermfg=12 ctermbg=6 gui=bold guifg=#ff1155
    DiffText                                                    { gui="bold", fg="#ff1155", }, -- DiffText       xxx cterm=bold ctermbg=9 gui=bold guifg=#ff1155
    SignColumn                                                  { fg="cyan", bg="#1e1e1e", }, -- SignColumn     xxx ctermfg=14 guifg=Cyan guibg=#1e1e1e
    CursorLineSign                                              { SignColumn }, -- CursorLineSign xxx links to SignColumn
    Conceal                                                     { fg="lightgrey", bg="darkgrey", }, -- Conceal        xxx ctermfg=7 ctermbg=242 guifg=LightGrey guibg=DarkGrey
    SpellBad                                                    { gui="undercurl", sp="red", }, -- SpellBad       xxx ctermbg=9 gui=undercurl guisp=Red
    SpellCap                                                    { gui="undercurl", sp="blue", }, -- SpellCap       xxx ctermbg=12 gui=undercurl guisp=Blue
    SpellRare                                                   { gui="undercurl", sp="magenta", }, -- SpellRare      xxx ctermbg=13 gui=undercurl guisp=Magenta
    SpellLocal                                                  { gui="undercurl", sp="cyan", }, -- SpellLocal     xxx ctermbg=14 gui=undercurl guisp=Cyan
    Pmenu                                                       { fg="#aaaaaa", bg=wolken, }, -- Pmenu          xxx ctermfg=0 ctermbg=13 guifg=#aaaaaa guibg=#444444
    PmenuKind                                                   { Pmenu }, -- PmenuKind      xxx links to Pmenu
    PmenuExtra                                                  { Pmenu }, -- PmenuExtra     xxx links to Pmenu
    NormalFloat                                                 { Pmenu }, -- NormalFloat    xxx links to Pmenu
    PmenuSel                                                    { fg="#11ff55", }, -- PmenuSel       xxx ctermfg=242 ctermbg=0 guifg=#11ff55
    PmenuKindSel                                                { PmenuSel }, -- PmenuKindSel   xxx links to PmenuSel
    PmenuExtraSel                                               { PmenuSel }, -- PmenuExtraSel  xxx links to PmenuSel
    PmenuSbar                                                   { bg="grey", }, -- PmenuSbar      xxx ctermbg=248 guibg=Grey
    PmenuThumb                                                  { bg="white", }, -- PmenuThumb     xxx ctermbg=15 guibg=White
    TabLine                                                     { fg=wolken, bg="#444444", }, -- TabLine        xxx cterm=underline ctermfg=15 ctermbg=242 guifg=#444444 guibg=#444444
    TabLineSel                                                  { gui="bold", }, -- TabLineSel     xxx cterm=bold gui=bold
    TabLineFill                                                 { bg=wolken, }, -- TabLineFill    xxx cterm=reverse guibg=#444444
    CursorColumn                                                { bg="grey40", }, -- CursorColumn   xxx ctermbg=242 guibg=Grey40
    CursorLine                                                  { bg=wolken, }, -- CursorLine     xxx cterm=underline guibg=#444444
    ColorColumn                                                 { bg="darkred", }, -- ColorColumn    xxx ctermbg=1 guibg=DarkRed
    WinBar                                                      { gui="bold", }, -- WinBar         xxx cterm=bold gui=bold
    WinBarNC                                                    { WinBar }, -- WinBarNC       xxx links to WinBar
    Cursor                                                      { fg="bg", bg="fg", }, -- Cursor         xxx guifg=bg guibg=fg
    lCursor                                                     { fg="bg", bg="fg", }, -- lCursor        xxx guifg=bg guibg=fg
    FloatShadow                                                 { blend=80, bg="black", }, -- FloatShadow    xxx guibg=Black blend=80
    FloatShadowThrough                                          { blend=100, bg="black", }, -- FloatShadowThrough xxx guibg=Black blend=100
    RedrawDebugNormal                                           { gui="reverse", }, -- RedrawDebugNormal xxx cterm=reverse gui=reverse
    RedrawDebugClear                                            { bg="yellow", }, -- RedrawDebugClear xxx ctermbg=11 guibg=Yellow
    RedrawDebugComposed                                         { bg="green", }, -- RedrawDebugComposed xxx ctermbg=10 guibg=Green
    RedrawDebugRecompose                                        { bg="red", }, -- RedrawDebugRecompose xxx ctermbg=9 guibg=Red
    Error                                                       { fg="#ff1155", }, -- Error          xxx ctermfg=15 ctermbg=9 guifg=#ff1155
    NvimInvalid                                                 { Error }, -- NvimInvalid    xxx links to Error
    Todo                                                        { fg="#ffbb33", }, -- Todo           xxx ctermfg=0 ctermbg=11 guifg=#ffbb33
    String                                                      { fg="#ffbb33", }, -- String         xxx guifg=#ffbb33
    sym"@string"                                                { String }, -- @string        xxx links to String
    NvimString                                                  { String }, -- NvimString     xxx links to String
    Constant                                                    { fg="#11ff55", }, -- Constant       xxx ctermfg=13 guifg=#11ff55
    Character                                                   { Constant }, -- Character      xxx links to Constant
    Boolean                                                     { Constant }, -- Boolean        xxx links to Constant
    sym"@constant"                                              { Constant }, -- @constant      xxx links to Constant
    Number                                                      { fg="#ffbb33", }, -- Number         xxx guifg=#ffbb33
    Float                                                       { Number }, -- Float          xxx links to Number
    sym"@number"                                                { Number }, -- @number        xxx links to Number
    NvimNumber                                                  { Number }, -- NvimNumber     xxx links to Number
    StartifyNumber                                              { Number }, -- StartifyNumber xxx links to Number
    Function                                                    { fg="#66ffdd", }, -- Function       xxx guifg=#66ffdd
    sym"@function"                                              { Function }, -- @function      xxx links to Function
    sym"@method"                                                { Function }, -- @method        xxx links to Function
    LspInfoList                                                 { Function }, -- LspInfoList    xxx links to Function
    WhichKey                                                    { Function }, -- WhichKey       xxx links to Function
    Identifier                                                  { fg="#ff1155", }, -- Identifier     xxx cterm=bold ctermfg=14 guifg=#ff1155
    sym"@parameter"                                             { Identifier }, -- @parameter     xxx links to Identifier
    sym"@field"                                                 { Identifier }, -- @field         xxx links to Identifier
    sym"@property"                                              { Identifier }, -- @property      xxx links to Identifier
    sym"@variable"                                              { Identifier }, -- @variable      xxx links to Identifier
    sym"@namespace"                                             { Identifier }, -- @namespace     xxx links to Identifier
    NvimIdentifier                                              { Identifier }, -- NvimIdentifier xxx links to Identifier
    StartifyFile                                                { Identifier }, -- StartifyFile   xxx links to Identifier
    WhichKeyDesc                                                { Identifier }, -- WhichKeyDesc   xxx links to Identifier
    Conditional                                                 { fg="#ffbb33", }, -- Conditional    xxx guifg=#ffbb33
    sym"@conditional"                                           { Conditional }, -- @conditional   xxx links to Conditional
    Statement                                                   { gui="bold", fg="#1155ff", }, -- Statement      xxx ctermfg=11 gui=bold guifg=#1155ff
    StartifySection                                             { Statement }, -- StartifySection xxx links to Statement
    Repeat                                                      { fg="#11ff55", }, -- Repeat         xxx guifg=#11ff55
    sym"@repeat"                                                { Repeat }, -- @repeat        xxx links to Repeat
    Label                                                       { fg="#ffbb33", }, -- Label          xxx guifg=#ffbb33
    sym"@label"                                                 { Label }, -- @label         xxx links to Label
    LspInfoBorder                                               { Label }, -- LspInfoBorder  xxx links to Label
    Operator                                                    { fg="#1155ff", }, -- Operator       xxx guifg=#1155ff
    sym"@operator"                                              { Operator }, -- @operator      xxx links to Operator
    NvimAssignment                                              { Operator }, -- NvimAssignment xxx links to Operator
    NvimOperator                                                { Operator }, -- NvimOperator   xxx links to Operator
    Keyword                                                     { fg="#11ff55", }, -- Keyword        xxx guifg=#11ff55
    sym"@keyword"                                               { Keyword }, -- @keyword       xxx links to Keyword
    WhichKeyGroup                                               { Keyword }, -- WhichKeyGroup  xxx links to Keyword
    Exception                                                   { fg="#ff1155", }, -- Exception      xxx guifg=#ff1155
    sym"@exception"                                             { Exception }, -- @exception     xxx links to Exception
    Include                                                     { fg="#ffdd66", }, -- Include        xxx guifg=#ffdd66
    sym"@include"                                               { Include }, -- @include       xxx links to Include
    PreProc                                                     { fg="#ff1155", }, -- PreProc        xxx ctermfg=81 guifg=#ff1155
    sym"@preproc"                                               { PreProc }, -- @preproc       xxx links to PreProc
    Define                                                      { fg="#ffbb33", }, -- Define         xxx guifg=#ffbb33
    sym"@define"                                                { Define }, -- @define        xxx links to Define
    Macro                                                       { fg="#ffbb33", }, -- Macro          xxx guifg=#ffbb33
    sym"@macro"                                                 { Macro }, -- @macro         xxx links to Macro
    PreCondit                                                   { fg="#ffbb33", }, -- PreCondit      xxx guifg=#ffbb33
    Type                                                        { gui="bold", fg="#ff1155", }, -- Type           xxx ctermfg=121 gui=bold guifg=#ff1155
    StorageClass                                                { Type }, -- StorageClass   xxx links to Type
    Structure                                                   { Type }, -- Structure      xxx links to Type
    Typedef                                                     { Type }, -- Typedef        xxx links to Type
    sym"@type"                                                  { Type }, -- @type          xxx links to Type
    NvimNumberPrefix                                            { Type }, -- NvimNumberPrefix xxx links to Type
    NvimOptionSigil                                             { Type }, -- NvimOptionSigil xxx links to Type
    LspInfoFiletype                                             { Type }, -- LspInfoFiletype xxx links to Type
    Tag                                                         { fg="#ffbb33", }, -- Tag            xxx guifg=#ffbb33
    sym"@tag"                                                   { Tag }, -- @tag           xxx links to Tag
    Special                                                     { fg="#ffbb33", }, -- Special        xxx ctermfg=224 guifg=#ffbb33
    sym"@constructor"                                           { Special }, -- @constructor   xxx links to Special
    SpecialChar                                                 { fg="#ffbb33", }, -- SpecialChar    xxx guifg=#ffbb33
    NvimRegister                                                { SpecialChar }, -- NvimRegister   xxx links to SpecialChar
    NvimStringSpecial                                           { SpecialChar }, -- NvimStringSpecial xxx links to SpecialChar
    Delimiter                                                   { fg="#ffbb33", }, -- Delimiter      xxx guifg=#ffbb33
    sym"@punctuation"                                           { Delimiter }, -- @punctuation   xxx links to Delimiter
    NvimParenthesis                                             { Delimiter }, -- NvimParenthesis xxx links to Delimiter
    NvimColon                                                   { Delimiter }, -- NvimColon      xxx links to Delimiter
    NvimComma                                                   { Delimiter }, -- NvimComma      xxx links to Delimiter
    NvimArrow                                                   { Delimiter }, -- NvimArrow      xxx links to Delimiter
    StartifyBracket                                             { Delimiter }, -- StartifyBracket xxx links to Delimiter
    StartifySlash                                               { Delimiter }, -- StartifySlash  xxx links to Delimiter
    SpecialComment                                              { gui="italic", fg=wolken, }, -- SpecialComment xxx gui=italic guifg=#ff4488
    Debug                                                       { fg="#ffbb33", }, -- Debug          xxx guifg=#ffbb33
    sym"@debug"                                                 { Debug }, -- @debug         xxx links to Debug
    DiagnosticError                                             { fg="red", }, -- DiagnosticError xxx ctermfg=1 guifg=Red
    DiagnosticVirtualTextError                                  { DiagnosticError }, -- DiagnosticVirtualTextError xxx links to DiagnosticError
    DiagnosticFloatingError                                     { DiagnosticError }, -- DiagnosticFloatingError xxx links to DiagnosticError
    DiagnosticSignError                                         { DiagnosticError }, -- DiagnosticSignError xxx links to DiagnosticError
    DiagnosticWarn                                              { fg="orange", }, -- DiagnosticWarn xxx ctermfg=3 guifg=Orange
    DiagnosticVirtualTextWarn                                   { DiagnosticWarn }, -- DiagnosticVirtualTextWarn xxx links to DiagnosticWarn
    DiagnosticFloatingWarn                                      { DiagnosticWarn }, -- DiagnosticFloatingWarn xxx links to DiagnosticWarn
    DiagnosticSignWarn                                          { DiagnosticWarn }, -- DiagnosticSignWarn xxx links to DiagnosticWarn
    DiagnosticInfo                                              { fg="lightblue", }, -- DiagnosticInfo xxx ctermfg=4 guifg=LightBlue
    DiagnosticVirtualTextInfo                                   { DiagnosticInfo }, -- DiagnosticVirtualTextInfo xxx links to DiagnosticInfo
    DiagnosticFloatingInfo                                      { DiagnosticInfo }, -- DiagnosticFloatingInfo xxx links to DiagnosticInfo
    DiagnosticSignInfo                                          { DiagnosticInfo }, -- DiagnosticSignInfo xxx links to DiagnosticInfo
    DiagnosticHint                                              { fg="lightgrey", }, -- DiagnosticHint xxx ctermfg=7 guifg=LightGrey
    DiagnosticVirtualTextHint                                   { DiagnosticHint }, -- DiagnosticVirtualTextHint xxx links to DiagnosticHint
    DiagnosticFloatingHint                                      { DiagnosticHint }, -- DiagnosticFloatingHint xxx links to DiagnosticHint
    DiagnosticSignHint                                          { DiagnosticHint }, -- DiagnosticSignHint xxx links to DiagnosticHint
    DiagnosticOk                                                { fg="lightgreen", }, -- DiagnosticOk   xxx ctermfg=10 guifg=LightGreen
    DiagnosticVirtualTextOk                                     { DiagnosticOk }, -- DiagnosticVirtualTextOk xxx links to DiagnosticOk
    DiagnosticFloatingOk                                        { DiagnosticOk }, -- DiagnosticFloatingOk xxx links to DiagnosticOk
    DiagnosticSignOk                                            { DiagnosticOk }, -- DiagnosticSignOk xxx links to DiagnosticOk
    DiagnosticUnderlineError                                    { gui="underline", sp="red", }, -- DiagnosticUnderlineError xxx cterm=underline gui=underline guisp=Red
    DiagnosticUnderlineWarn                                     { gui="underline", sp="orange", }, -- DiagnosticUnderlineWarn xxx cterm=underline gui=underline guisp=Orange
    DiagnosticUnderlineInfo                                     { gui="underline", sp="lightblue", }, -- DiagnosticUnderlineInfo xxx cterm=underline gui=underline guisp=LightBlue
    DiagnosticUnderlineHint                                     { gui="underline", sp="lightgrey", }, -- DiagnosticUnderlineHint xxx cterm=underline gui=underline guisp=LightGrey
    DiagnosticUnderlineOk                                       { gui="underline", sp="lightgreen", }, -- DiagnosticUnderlineOk xxx cterm=underline gui=underline guisp=LightGreen
    DiagnosticDeprecated                                        { gui="strikethrough", sp="red", }, -- DiagnosticDeprecated xxx cterm=strikethrough gui=strikethrough guisp=Red
    Comment                                                     { gui="italic", fg=wolken, }, -- Comment        xxx ctermfg=14 gui=italic guifg=#ff4488
    DiagnosticUnnecessary                                       { Comment }, -- DiagnosticUnnecessary xxx links to Comment
    sym"@comment"                                               { Comment }, -- @comment       xxx links to Comment
    sym"@lsp.type.comment"                                      { Comment }, -- @lsp.type.comment xxx links to Comment
    LspInfoTip                                                  { Comment }, -- LspInfoTip     xxx links to Comment
    StartifySpecial                                             { Comment }, -- StartifySpecial xxx links to Comment
    WhichKeyValue                                               { Comment }, -- WhichKeyValue  xxx links to Comment
    WhichKeySeparator                                           { Comment }, -- WhichKeySeparator xxx links to Comment
    Underlined                                                  { gui="underline", fg="#80a0ff", }, -- Underlined     xxx cterm=underline ctermfg=81 gui=underline guifg=#80a0ff
    sym"@text.underline"                                        { Underlined }, -- @text.underline xxx links to Underlined
    MatchParen                                                  { fg="#ffbb33", }, -- MatchParen     xxx ctermbg=6 guifg=#ffbb33
    Ignore                                                      { fg="bg", }, -- Ignore         xxx ctermfg=0 guifg=bg
    NvimInternalError                                           { fg="red", bg="red", }, -- NvimInternalError xxx ctermfg=9 ctermbg=9 guifg=Red guibg=Red
    NvimFigureBrace                                             { NvimInternalError }, -- NvimFigureBrace xxx links to NvimInternalError
    NvimSingleQuotedUnknownEscape                               { NvimInternalError }, -- NvimSingleQuotedUnknownEscape xxx links to NvimInternalError
    NvimInvalidSingleQuotedUnknownEscape                        { NvimInternalError }, -- NvimInvalidSingleQuotedUnknownEscape xxx links to NvimInternalError
    CmpItemAbbrDefault                                          { fg="#aaaaaa", }, -- CmpItemAbbrDefault xxx guifg=#aaaaaa
    CmpItemAbbr                                                 { CmpItemAbbrDefault }, -- CmpItemAbbr    xxx links to CmpItemAbbrDefault
    CmpItemAbbrDeprecatedDefault                                { fg=wolken, }, -- CmpItemAbbrDeprecatedDefault xxx guifg=#ff4488
    CmpItemAbbrDeprecated                                       { CmpItemAbbrDeprecatedDefault }, -- CmpItemAbbrDeprecated xxx links to CmpItemAbbrDeprecatedDefault
    CmpItemAbbrMatchDefault                                     { fg="#aaaaaa", }, -- CmpItemAbbrMatchDefault xxx guifg=#aaaaaa
    CmpItemAbbrMatch                                            { CmpItemAbbrMatchDefault }, -- CmpItemAbbrMatch xxx links to CmpItemAbbrMatchDefault
    CmpItemAbbrMatchFuzzyDefault                                { fg="#aaaaaa", }, -- CmpItemAbbrMatchFuzzyDefault xxx guifg=#aaaaaa
    CmpItemAbbrMatchFuzzy                                       { CmpItemAbbrMatchFuzzyDefault }, -- CmpItemAbbrMatchFuzzy xxx links to CmpItemAbbrMatchFuzzyDefault
    CmpItemKindDefault                                          { fg="#ffbb33", }, -- CmpItemKindDefault xxx guifg=#ffbb33
    CmpItemKind                                                 { CmpItemKindDefault }, -- CmpItemKind    xxx links to CmpItemKindDefault
    CmpItemMenuDefault                                          { fg="#aaaaaa", }, -- CmpItemMenuDefault xxx guifg=#aaaaaa
    CmpItemMenu                                                 { CmpItemMenuDefault }, -- CmpItemMenu    xxx links to CmpItemMenuDefault
    NoiceCursor                                                 { }, -- NoiceCursor    xxx cterm= gui=
    markdownLinkText                                            { fg="#ffdd66", }, -- markdownLinkText xxx guifg=#ffdd66
    cssImportant                                                { fg="#ff1155", }, -- cssImportant   xxx guifg=#ff1155
    cssColor                                                    { fg="#ffbb33", }, -- cssColor       xxx guifg=#ffbb33
    cssClassName                                                { fg="#ffdd66", }, -- cssClassName   xxx guifg=#ffdd66
    cssIdentifier                                               { fg="#ff1155", }, -- cssIdentifier  xxx guifg=#ff1155
    lualine_b_inactive                                          { fg="#ffffff", bg="#1e1e1e", }, -- lualine_b_inactive xxx guifg=#ffffff guibg=#1e1e1e
    lualine_a_inactive                                          { gui="bold", fg="#1e1e1e", bg="#ffffff", }, -- lualine_a_inactive xxx gui=bold guifg=#1e1e1e guibg=#ffffff
    lualine_c_inactive                                          { fg="#aaaaaa", bg=wolken, }, -- lualine_c_inactive xxx guifg=#aaaaaa guibg=#444444
    lualine_b_visual                                            { fg="#ffbb33", bg="#1e1e1e", }, -- lualine_b_visual xxx guifg=#ffbb33 guibg=#1e1e1e
    lualine_a_visual                                            { gui="bold", fg="#1e1e1e", bg="#ffbb33", }, -- lualine_a_visual xxx gui=bold guifg=#1e1e1e guibg=#ffbb33
    lualine_c_visual                                            { fg="#aaaaaa", bg=wolken, }, -- lualine_c_visual xxx guifg=#aaaaaa guibg=#444444
    lualine_b_normal                                            { fg="#ffffff", bg="#1e1e1e", }, -- lualine_b_normal xxx guifg=#ffffff guibg=#1e1e1e
    lualine_a_normal                                            { gui="bold", fg="#1e1e1e", bg="#ffffff", }, -- lualine_a_normal xxx gui=bold guifg=#1e1e1e guibg=#ffffff
    lualine_c_normal                                            { fg="#aaaaaa", bg=wolken, }, -- lualine_c_normal xxx guifg=#aaaaaa guibg=#444444
    lualine_b_insert                                            { fg="#ffbb33", bg="#1e1e1e", }, -- lualine_b_insert xxx guifg=#ffbb33 guibg=#1e1e1e
    lualine_a_insert                                            { gui="bold", fg="#1e1e1e", bg="#ffbb33", }, -- lualine_a_insert xxx gui=bold guifg=#1e1e1e guibg=#ffbb33
    lualine_c_insert                                            { fg="#aaaaaa", bg=wolken, }, -- lualine_c_insert xxx guifg=#aaaaaa guibg=#444444
    lualine_b_command                                           { fg="#ff1155", bg="#1e1e1e", }, -- lualine_b_command xxx guifg=#ff1155 guibg=#1e1e1e
    lualine_a_command                                           { gui="bold", fg="#1e1e1e", bg="#ff1155", }, -- lualine_a_command xxx gui=bold guifg=#1e1e1e guibg=#ff1155
    lualine_c_command                                           { fg="#aaaaaa", bg=wolken, }, -- lualine_c_command xxx guifg=#aaaaaa guibg=#444444
    lualine_b_replace                                           { fg="#ffbb33", bg="#1e1e1e", }, -- lualine_b_replace xxx guifg=#ffbb33 guibg=#1e1e1e
    lualine_a_replace                                           { gui="bold", fg="#1e1e1e", bg="#ffbb33", }, -- lualine_a_replace xxx gui=bold guifg=#1e1e1e guibg=#ffbb33
    lualine_c_replace                                           { fg="#aaaaaa", bg=wolken, }, -- lualine_c_replace xxx guifg=#aaaaaa guibg=#444444
    lualine_b_diff_added_normal                                 { fg="#11ff55", bg="#1e1e1e", }, -- lualine_b_diff_added_normal xxx guifg=#11ff55 guibg=#1e1e1e
    lualine_b_diff_added_insert                                 { fg="#11ff55", bg="#1e1e1e", }, -- lualine_b_diff_added_insert xxx guifg=#11ff55 guibg=#1e1e1e
    lualine_b_diff_added_visual                                 { fg="#11ff55", bg="#1e1e1e", }, -- lualine_b_diff_added_visual xxx guifg=#11ff55 guibg=#1e1e1e
    lualine_b_diff_added_replace                                { fg="#11ff55", bg="#1e1e1e", }, -- lualine_b_diff_added_replace xxx guifg=#11ff55 guibg=#1e1e1e
    lualine_b_diff_added_command                                { fg="#11ff55", bg="#1e1e1e", }, -- lualine_b_diff_added_command xxx guifg=#11ff55 guibg=#1e1e1e
    lualine_b_diff_added_terminal                               { fg="#11ff55", bg="#1e1e1e", }, -- lualine_b_diff_added_terminal xxx guifg=#11ff55 guibg=#1e1e1e
    lualine_b_diff_added_inactive                               { fg="#11ff55", bg="#1e1e1e", }, -- lualine_b_diff_added_inactive xxx guifg=#11ff55 guibg=#1e1e1e
    lualine_b_diff_modified_normal                              { fg="#ffbb33", bg="#1e1e1e", }, -- lualine_b_diff_modified_normal xxx guifg=#ffbb33 guibg=#1e1e1e
    lualine_b_diff_modified_insert                              { fg="#ffbb33", bg="#1e1e1e", }, -- lualine_b_diff_modified_insert xxx guifg=#ffbb33 guibg=#1e1e1e
    lualine_b_diff_modified_visual                              { fg="#ffbb33", bg="#1e1e1e", }, -- lualine_b_diff_modified_visual xxx guifg=#ffbb33 guibg=#1e1e1e
    lualine_b_diff_modified_replace                             { fg="#ffbb33", bg="#1e1e1e", }, -- lualine_b_diff_modified_replace xxx guifg=#ffbb33 guibg=#1e1e1e
    lualine_b_diff_modified_command                             { fg="#ffbb33", bg="#1e1e1e", }, -- lualine_b_diff_modified_command xxx guifg=#ffbb33 guibg=#1e1e1e
    lualine_b_diff_modified_terminal                            { fg="#ffbb33", bg="#1e1e1e", }, -- lualine_b_diff_modified_terminal xxx guifg=#ffbb33 guibg=#1e1e1e
    lualine_b_diff_modified_inactive                            { fg="#ffbb33", bg="#1e1e1e", }, -- lualine_b_diff_modified_inactive xxx guifg=#ffbb33 guibg=#1e1e1e
    lualine_b_diff_removed_normal                               { fg="#ff1155", bg="#1e1e1e", }, -- lualine_b_diff_removed_normal xxx guifg=#ff1155 guibg=#1e1e1e
    lualine_b_diff_removed_insert                               { fg="#ff1155", bg="#1e1e1e", }, -- lualine_b_diff_removed_insert xxx guifg=#ff1155 guibg=#1e1e1e
    lualine_b_diff_removed_visual                               { fg="#ff1155", bg="#1e1e1e", }, -- lualine_b_diff_removed_visual xxx guifg=#ff1155 guibg=#1e1e1e
    lualine_b_diff_removed_replace                              { fg="#ff1155", bg="#1e1e1e", }, -- lualine_b_diff_removed_replace xxx guifg=#ff1155 guibg=#1e1e1e
    lualine_b_diff_removed_command                              { fg="#ff1155", bg="#1e1e1e", }, -- lualine_b_diff_removed_command xxx guifg=#ff1155 guibg=#1e1e1e
    lualine_b_diff_removed_terminal                             { fg="#ff1155", bg="#1e1e1e", }, -- lualine_b_diff_removed_terminal xxx guifg=#ff1155 guibg=#1e1e1e
    lualine_b_diff_removed_inactive                             { fg="#ff1155", bg="#1e1e1e", }, -- lualine_b_diff_removed_inactive xxx guifg=#ff1155 guibg=#1e1e1e
    lualine_b_diagnostics_error_normal                          { fg="#ff0000", bg="#1e1e1e", }, -- lualine_b_diagnostics_error_normal xxx guifg=#ff0000 guibg=#1e1e1e
    lualine_b_diagnostics_error_insert                          { fg="#ff0000", bg="#1e1e1e", }, -- lualine_b_diagnostics_error_insert xxx guifg=#ff0000 guibg=#1e1e1e
    lualine_b_diagnostics_error_visual                          { fg="#ff0000", bg="#1e1e1e", }, -- lualine_b_diagnostics_error_visual xxx guifg=#ff0000 guibg=#1e1e1e
    lualine_b_diagnostics_error_replace                         { fg="#ff0000", bg="#1e1e1e", }, -- lualine_b_diagnostics_error_replace xxx guifg=#ff0000 guibg=#1e1e1e
    lualine_b_diagnostics_error_command                         { fg="#ff0000", bg="#1e1e1e", }, -- lualine_b_diagnostics_error_command xxx guifg=#ff0000 guibg=#1e1e1e
    lualine_b_diagnostics_error_terminal                        { fg="#ff0000", bg="#1e1e1e", }, -- lualine_b_diagnostics_error_terminal xxx guifg=#ff0000 guibg=#1e1e1e
    lualine_b_diagnostics_error_inactive                        { fg="#ff0000", bg="#1e1e1e", }, -- lualine_b_diagnostics_error_inactive xxx guifg=#ff0000 guibg=#1e1e1e
    lualine_b_diagnostics_warn_normal                           { fg="#ffa500", bg="#1e1e1e", }, -- lualine_b_diagnostics_warn_normal xxx guifg=#ffa500 guibg=#1e1e1e
    lualine_b_diagnostics_warn_insert                           { fg="#ffa500", bg="#1e1e1e", }, -- lualine_b_diagnostics_warn_insert xxx guifg=#ffa500 guibg=#1e1e1e
    lualine_b_diagnostics_warn_visual                           { fg="#ffa500", bg="#1e1e1e", }, -- lualine_b_diagnostics_warn_visual xxx guifg=#ffa500 guibg=#1e1e1e
    lualine_b_diagnostics_warn_replace                          { fg="#ffa500", bg="#1e1e1e", }, -- lualine_b_diagnostics_warn_replace xxx guifg=#ffa500 guibg=#1e1e1e
    lualine_b_diagnostics_warn_command                          { fg="#ffa500", bg="#1e1e1e", }, -- lualine_b_diagnostics_warn_command xxx guifg=#ffa500 guibg=#1e1e1e
    lualine_b_diagnostics_warn_terminal                         { fg="#ffa500", bg="#1e1e1e", }, -- lualine_b_diagnostics_warn_terminal xxx guifg=#ffa500 guibg=#1e1e1e
    lualine_b_diagnostics_warn_inactive                         { fg="#ffa500", bg="#1e1e1e", }, -- lualine_b_diagnostics_warn_inactive xxx guifg=#ffa500 guibg=#1e1e1e
    lualine_b_diagnostics_info_normal                           { fg="#add8e6", bg="#1e1e1e", }, -- lualine_b_diagnostics_info_normal xxx guifg=#add8e6 guibg=#1e1e1e
    lualine_b_diagnostics_info_insert                           { fg="#add8e6", bg="#1e1e1e", }, -- lualine_b_diagnostics_info_insert xxx guifg=#add8e6 guibg=#1e1e1e
    lualine_b_diagnostics_info_visual                           { fg="#add8e6", bg="#1e1e1e", }, -- lualine_b_diagnostics_info_visual xxx guifg=#add8e6 guibg=#1e1e1e
    lualine_b_diagnostics_info_replace                          { fg="#add8e6", bg="#1e1e1e", }, -- lualine_b_diagnostics_info_replace xxx guifg=#add8e6 guibg=#1e1e1e
    lualine_b_diagnostics_info_command                          { fg="#add8e6", bg="#1e1e1e", }, -- lualine_b_diagnostics_info_command xxx guifg=#add8e6 guibg=#1e1e1e
    lualine_b_diagnostics_info_terminal                         { fg="#add8e6", bg="#1e1e1e", }, -- lualine_b_diagnostics_info_terminal xxx guifg=#add8e6 guibg=#1e1e1e
    lualine_b_diagnostics_info_inactive                         { fg="#add8e6", bg="#1e1e1e", }, -- lualine_b_diagnostics_info_inactive xxx guifg=#add8e6 guibg=#1e1e1e
    lualine_b_diagnostics_hint_normal                           { fg="#d3d3d3", bg="#1e1e1e", }, -- lualine_b_diagnostics_hint_normal xxx guifg=#d3d3d3 guibg=#1e1e1e
    lualine_b_diagnostics_hint_insert                           { fg="#d3d3d3", bg="#1e1e1e", }, -- lualine_b_diagnostics_hint_insert xxx guifg=#d3d3d3 guibg=#1e1e1e
    lualine_b_diagnostics_hint_visual                           { fg="#d3d3d3", bg="#1e1e1e", }, -- lualine_b_diagnostics_hint_visual xxx guifg=#d3d3d3 guibg=#1e1e1e
    lualine_b_diagnostics_hint_replace                          { fg="#d3d3d3", bg="#1e1e1e", }, -- lualine_b_diagnostics_hint_replace xxx guifg=#d3d3d3 guibg=#1e1e1e
    lualine_b_diagnostics_hint_command                          { fg="#d3d3d3", bg="#1e1e1e", }, -- lualine_b_diagnostics_hint_command xxx guifg=#d3d3d3 guibg=#1e1e1e
    lualine_b_diagnostics_hint_terminal                         { fg="#d3d3d3", bg="#1e1e1e", }, -- lualine_b_diagnostics_hint_terminal xxx guifg=#d3d3d3 guibg=#1e1e1e
    lualine_b_diagnostics_hint_inactive                         { fg="#d3d3d3", bg="#1e1e1e", }, -- lualine_b_diagnostics_hint_inactive xxx guifg=#d3d3d3 guibg=#1e1e1e
    NoiceCmdlineIconInput                                       { }, -- NoiceCmdlineIconInput xxx cterm= gui=
    NoiceCmdlineIcon                                            { }, -- NoiceCmdlineIcon xxx cterm= gui=
    NoiceCmdlinePopupBorderInput                                { }, -- NoiceCmdlinePopupBorderInput xxx cterm= gui=
    NoiceCmdlinePopupBorder                                     { }, -- NoiceCmdlinePopupBorder xxx cterm= gui=
    NoiceCmdlineIconCmdline                                     { }, -- NoiceCmdlineIconCmdline xxx cterm= gui=
    NoiceCmdlinePopupBorderCmdline                              { }, -- NoiceCmdlinePopupBorderCmdline xxx cterm= gui=
    NoiceCmdlineIconHelp                                        { }, -- NoiceCmdlineIconHelp xxx cterm= gui=
    NoiceCmdlinePopupBorderHelp                                 { }, -- NoiceCmdlinePopupBorderHelp xxx cterm= gui=
    NoiceScrollbarThumb                                         { }, -- NoiceScrollbarThumb xxx cterm= gui=
    NoiceScrollbar                                              { }, -- NoiceScrollbar xxx cterm= gui=
    NoicePopupmenuSelected                                      { }, -- NoicePopupmenuSelected xxx cterm= gui=
    NoicePopupmenuMatch                                         { }, -- NoicePopupmenuMatch xxx cterm= gui=
    NoicePopupmenuBorder                                        { }, -- NoicePopupmenuBorder xxx cterm= gui=
    NoicePopupmenu                                              { }, -- NoicePopupmenu xxx cterm= gui=
    NoicePopupBorder                                            { }, -- NoicePopupBorder xxx cterm= gui=
    NoicePopup                                                  { }, -- NoicePopup     xxx cterm= gui=
    NoiceConfirmBorder                                          { }, -- NoiceConfirmBorder xxx cterm= gui=
    NoiceConfirm                                                { }, -- NoiceConfirm   xxx cterm= gui=
    NoiceCmdlinePopupBorderSearch                               { }, -- NoiceCmdlinePopupBorderSearch xxx cterm= gui=
    NoiceCmdlinePopupTitle                                      { }, -- NoiceCmdlinePopupTitle xxx cterm= gui=
    NoiceCmdlinePopup                                           { }, -- NoiceCmdlinePopup xxx cterm= gui=
    NoiceCmdlinePrompt                                          { }, -- NoiceCmdlinePrompt xxx cterm= gui=
    NoiceCmdlineIconSearch                                      { }, -- NoiceCmdlineIconSearch xxx cterm= gui=
    NoiceMini                                                   { }, -- NoiceMini      xxx cterm= gui=
    NoiceFormatProgressTodo                                     { }, -- NoiceFormatProgressTodo xxx cterm= gui=
    NoiceCompletionItemKindMethod                               { }, -- NoiceCompletionItemKindMethod xxx cterm= gui=
    NoiceCompletionItemKindDefault                              { }, -- NoiceCompletionItemKindDefault xxx cterm= gui=
    NoiceCompletionItemKindEnum                                 { }, -- NoiceCompletionItemKindEnum xxx cterm= gui=
    NoiceCompletionItemKindVariable                             { }, -- NoiceCompletionItemKindVariable xxx cterm= gui=
    NoiceCompletionItemKindFile                                 { }, -- NoiceCompletionItemKindFile xxx cterm= gui=
    NoiceCompletionItemKindField                                { }, -- NoiceCompletionItemKindField xxx cterm= gui=
    NoiceCompletionItemKindUnit                                 { }, -- NoiceCompletionItemKindUnit xxx cterm= gui=
    NoiceCompletionItemKindEnumMember                           { }, -- NoiceCompletionItemKindEnumMember xxx cterm= gui=
    NoiceCompletionItemKindText                                 { }, -- NoiceCompletionItemKindText xxx cterm= gui=
    NoiceCompletionItemKindFolder                               { }, -- NoiceCompletionItemKindFolder xxx cterm= gui=
    NoiceCompletionItemKindSnippet                              { }, -- NoiceCompletionItemKindSnippet xxx cterm= gui=
    NoiceCompletionItemKindConstant                             { }, -- NoiceCompletionItemKindConstant xxx cterm= gui=
    NoiceCompletionItemKindProperty                             { }, -- NoiceCompletionItemKindProperty xxx cterm= gui=
    NoiceCmdlineIconCalculator                                  { }, -- NoiceCmdlineIconCalculator xxx cterm= gui=
    NoiceCmdlinePopupBorderCalculator                           { }, -- NoiceCmdlinePopupBorderCalculator xxx cterm= gui=
    NoiceCmdlinePopupBorderIncRename                            { }, -- NoiceCmdlinePopupBorderIncRename xxx cterm= gui=
    NoiceCmdlineIconIncRename                                   { }, -- NoiceCmdlineIconIncRename xxx cterm= gui=
    NoiceCmdlinePopupBorderFilter                               { }, -- NoiceCmdlinePopupBorderFilter xxx cterm= gui=
    NoiceCmdlineIconFilter                                      { }, -- NoiceCmdlineIconFilter xxx cterm= gui=
    NoiceCmdlineIconLua                                         { }, -- NoiceCmdlineIconLua xxx cterm= gui=
    NoiceCompletionItemKindValue                                { }, -- NoiceCompletionItemKindValue xxx cterm= gui=
    NoiceCompletionItemKindKeyword                              { }, -- NoiceCompletionItemKindKeyword xxx cterm= gui=
    NoiceCompletionItemKindStruct                               { }, -- NoiceCompletionItemKindStruct xxx cterm= gui=
    NoiceCompletionItemKindInterface                            { }, -- NoiceCompletionItemKindInterface xxx cterm= gui=
    NoiceCompletionItemKindConstructor                          { }, -- NoiceCompletionItemKindConstructor xxx cterm= gui=
    NoiceCompletionItemKindClass                                { }, -- NoiceCompletionItemKindClass xxx cterm= gui=
    NoiceCompletionItemKindFunction                             { }, -- NoiceCompletionItemKindFunction xxx cterm= gui=
    NoiceCompletionItemKindModule                               { }, -- NoiceCompletionItemKindModule xxx cterm= gui=
    NoiceCompletionItemKindColor                                { }, -- NoiceCompletionItemKindColor xxx cterm= gui=
    NoiceLspProgressClient                                      { }, -- NoiceLspProgressClient xxx cterm= gui=
    NoiceLspProgressTitle                                       { }, -- NoiceLspProgressTitle xxx cterm= gui=
    NoiceLspProgressSpinner                                     { }, -- NoiceLspProgressSpinner xxx cterm= gui=
    NoiceFormatLevelError                                       { }, -- NoiceFormatLevelError xxx cterm= gui=
    NoiceFormatLevelWarn                                        { }, -- NoiceFormatLevelWarn xxx cterm= gui=
    NoiceFormatLevelInfo                                        { }, -- NoiceFormatLevelInfo xxx cterm= gui=
    NoiceFormatLevelOff                                         { }, -- NoiceFormatLevelOff xxx cterm= gui=
    NoiceFormatLevelTrace                                       { }, -- NoiceFormatLevelTrace xxx cterm= gui=
    NoiceFormatLevelDebug                                       { }, -- NoiceFormatLevelDebug xxx cterm= gui=
    NoiceFormatTitle                                            { }, -- NoiceFormatTitle xxx cterm= gui=
    NoiceFormatConfirmDefault                                   { }, -- NoiceFormatConfirmDefault xxx cterm= gui=
    NoiceFormatConfirm                                          { }, -- NoiceFormatConfirm xxx cterm= gui=
    NoiceFormatDate                                             { }, -- NoiceFormatDate xxx cterm= gui=
    NoiceFormatKind                                             { }, -- NoiceFormatKind xxx cterm= gui=
    NoiceFormatEvent                                            { }, -- NoiceFormatEvent xxx cterm= gui=
    NoiceCmdline                                                { }, -- NoiceCmdline   xxx cterm= gui=
    NoiceFormatProgressDone                                     { fg="#aaaaaa", bg=wolken, }, -- NoiceFormatProgressDone xxx cterm= gui= guifg=#aaaaaa guibg=#ff4488
    NoiceVirtualText                                            { }, -- NoiceVirtualText xxx cterm= gui=
    NoiceSplitBorder                                            { }, -- NoiceSplitBorder xxx cterm= gui=
    NoiceSplit                                                  { }, -- NoiceSplit     xxx cterm= gui=
    NoiceCmdlinePopupBorderLua                                  { }, -- NoiceCmdlinePopupBorderLua xxx cterm= gui=
    NoiceHiddenCursor                                           { gui="nocombine", blend=100, }, -- NoiceHiddenCursor xxx cterm=nocombine gui=nocombine blend=100
    lualine_transitional_lualine_a_normal_to_lualine_c_normal   { fg="#ffffff", bg=wolken, }, -- lualine_transitional_lualine_a_normal_to_lualine_c_normal xxx guifg=#ffffff guibg=#444444
    lualine_transitional_lualine_b_normal_to_lualine_c_normal   { fg="#1e1e1e", bg=wolken, }, -- lualine_transitional_lualine_b_normal_to_lualine_c_normal xxx guifg=#1e1e1e guibg=#444444
    lualine_transitional_lualine_a_normal_to_lualine_b_normal   { fg="#ffffff", bg="#1e1e1e", }, -- lualine_transitional_lualine_a_normal_to_lualine_b_normal xxx guifg=#ffffff guibg=#1e1e1e
    lualine_transitional_lualine_a_command_to_lualine_c_command { fg="#ff1155", bg=wolken, }, -- lualine_transitional_lualine_a_command_to_lualine_c_command xxx guifg=#ff1155 guibg=#444444
    lualine_transitional_lualine_b_command_to_lualine_c_command { fg="#1e1e1e", bg=wolken, }, -- lualine_transitional_lualine_b_command_to_lualine_c_command xxx guifg=#1e1e1e guibg=#444444
    lualine_transitional_lualine_a_command_to_lualine_b_command { fg="#ff1155", bg="#1e1e1e", }, -- lualine_transitional_lualine_a_command_to_lualine_b_command xxx guifg=#ff1155 guibg=#1e1e1e
    lualine_b_terminal                                          { fg="#ff1155", bg="#1e1e1e", }, -- lualine_b_terminal xxx guifg=#ff1155 guibg=#1e1e1e
    lualine_a_terminal                                          { gui="bold", fg="#1e1e1e", bg="#ff1155", }, -- lualine_a_terminal xxx gui=bold guifg=#1e1e1e guibg=#ff1155
    lualine_c_terminal                                          { fg="#aaaaaa", bg=wolken, }, -- lualine_c_terminal xxx guifg=#aaaaaa guibg=#444444
    GitGutterDelete                                             { fg="#ff1155", }, -- GitGutterDelete xxx guifg=#ff1155
    GitGutterChangeDelete                                       { fg="#ff1155", }, -- GitGutterChangeDelete xxx guifg=#ff1155
    GitGutterAdd                                                { fg="#11ff55", }, -- GitGutterAdd   xxx guifg=#11ff55
    cssIncludeKeyword                                           { fg="#11ff55", }, -- cssIncludeKeyword xxx guifg=#11ff55
    GitGutterChange                                             { fg="#ffbb33", }, -- GitGutterChange xxx guifg=#ffbb33
    javaScriptBoolean                                           { fg="#ffdd66", }, -- javaScriptBoolean xxx guifg=#ffdd66
    Storage                                                     { fg="#ffdd66", }, -- Storage        xxx guifg=#ffdd66
    cssClassNameDot                                             { fg="#ffdd66", }, -- cssClassNameDot xxx guifg=#ffdd66
    cssAttr                                                     { fg="#1155ff", }, -- cssAttr        xxx guifg=#1155ff
  }
end)
return theme
